ALTER TABLE eol_control ENGINE=InnoDB;
ALTER TABLE eol_info ENGINE=InnoDB;
ALTER TABLE eol_reports ENGINE=InnoDB;
ALTER TABLE gf_info ENGINE=InnoDB;
ALTER TABLE gf_reports ENGINE=InnoDB;
ALTER TABLE osv_dlsessions ENGINE=InnoDB;
ALTER TABLE system ENGINE=InnoDB;