INSERT INTO jjun0366_frontend.fields_metadata (metadata_id, table_name, field_name, title, short_title, format, min, max, table_group, field_group, tooltip, field_type, good_increase, field_order)
VALUES
(NULL, NULL, 'CashFlowAggregateAccrual', 'Cash Flow Aggregate Accrual', 'CF Agg Accural', 'osvnumber:2:true', NULL, NULL, -12, NULL, 'Operations is composed of only two sides, the financing side and the operations side. Scale the cash flow-based aggregate accruals measure for comparative basis.<br> <katex>Accruals Ratio = (NI - (CFO + CFI))/(NOA_{t} + NOA_{t-1})/2</katex>', NULL, NULL, 0),
(NULL, NULL, 'BalanceSheetAggregateAccrual', 'Balance Sheet Aggregate Accrual', 'BS. Agg Accrual', 'osvnumber:2:true', NULL, NULL, -12, NULL, 'Aggregate accruals are the change in Net Operating Assets (NOA) from one period to the next.<br> <katex>Aggregate Accruals = NOA_{t} - NOA_{t-1}</katex>', NULL, NULL, 0),
(NULL, NULL, 'NetOperatingAssets ', 'Net Operating Assets (NOA)', 'NOA', 'osvnumber:2:true', NULL, NULL, -12, NULL, 'Net operating assets (NOA) is the difference between operating assets and operating liabilities. NOA : (total assets – cash) – (total liabilities – total debt) ', NULL, 0, 0),
(NULL, NULL, 'SloanAccrualRatio', 'Sloan Accrual Ratio', 'Sloan', 'osvpercent:2:true', NULL, NULL, -12, NULL, 'Sloan found that companies with low accrual ratios outperform companies with high accrual ratios.<br><br>Over a 40-year period between 1962 and 2001, buying the lowest accrual companies and shorting the highest accrual companies resulted in an average annual compounded return of 18% compared to the S&P 500’s 7.4% annual return over the same period.', NULL, NULL, 0),
(NULL, NULL, 'CashFlowAccrualRatio', 'Cash Flow Accrual Ratio', 'CF Accrual', 'osvpercent:2:true', NULL, NULL, -12, NULL, 'Accruals are accounting adjustments for revenues that have been earned but are not yet recorded in the accounts, and expenses that have been incurred but are not yet recorded in the accounts.', NULL, NULL, 0),
(NULL, NULL, 'BalanceSheetAccrualRatiol', 'Balance Sheet Accrual Ratio', 'BS Accrual', 'osvpercent:2:true', NULL, NULL, -12, NULL, 'Balance sheet accrual can indicate whether capital is being used properly.<br><br>Accruals are accounting adjustments for revenues that have been earned but are not yet recorded in the accounts, and expenses that have been incurred but are not yet recorded in the accounts.', NULL, NULL, 0),
(NULL, NULL, 'InterestBurden', 'Interest Burden', 'Int. Burden', 'osvnumber:2:true', NULL, NULL, -11, NULL, 'EBT ÷ EBIT<br><br>Shows how interest is affecting profits. If a company has no debt, the ratio will be 1.', NULL, 0, 0),
(NULL, NULL, 'EquityMultiplier', 'Equity Multiplier', 'Eq. Multiplier', 'osvnumber:2:true', NULL, NULL, -11, NULL, 'Total Assets ÷ Shareholders Equity<br><br>Equity multiplier shows financial leverage.', NULL, 0, 0),
(NULL, NULL, 'TaxBurden', 'Tax Burden', 'Tax Burden', 'osvnumber:2:true', NULL, NULL, -11, NULL, 'Net Income ÷ EBT<br><br>Proportion of profits retained after paying taxes.', NULL, 0, 0),
(NULL, 'ttm_financialscustom', 'OperatingMarginPercent', 'Operating Income Margin', 'Op. Margin', 'osvpercent:2:true', NULL, NULL, -11, NULL, 'Net Income ÷ Sales<br><br>Net profit margin shows operating efficiency.', NULL, 1, 0)
;
