CREATE TABLE IF NOT EXISTS `ttm_ratings_history` (
  `ticker_id` bigint(20) NOT NULL,
  `ratings_date` date NOT NULL,
  `Q1` decimal(30,15) DEFAULT NULL,
  `Q2` decimal(30,15) DEFAULT NULL,
  `Q3` decimal(30,15) DEFAULT NULL,
  `QT` decimal(30,15) DEFAULT NULL,
  `V1` decimal(30,15) DEFAULT NULL,
  `V2` decimal(30,15) DEFAULT NULL,
  `V3` decimal(30,15) DEFAULT NULL,
  `V4` decimal(30,15) DEFAULT NULL,
  `VT` decimal(30,15) DEFAULT NULL,
  `G1` decimal(30,15) DEFAULT NULL,
  `G2` decimal(30,15) DEFAULT NULL,
  `G3` decimal(30,15) DEFAULT NULL,
  `G4` decimal(30,15) DEFAULT NULL,
  `GT` decimal(30,15) DEFAULT NULL,
  `AS` decimal(30,15) DEFAULT NULL,
  `AS_grade` char(1) DEFAULT NULL,
  `Q_grade` char(1) NOT NULL,
  `V_grade` char(1) NOT NULL,
  `G_grade` char(1) NOT NULL,
  PRIMARY KEY (`ticker_id`,`ratings_date`),
  KEY `QT` (`QT`),
  KEY `VT` (`VT`),
  KEY `GT` (`GT`),
  KEY `AS` (`AS`),
  KEY `Grade` (`AS_grade`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
