/* Creation of industry match */
CREATE TABLE `industry_match` (
  `industry_ticker` varchar(100) NOT NULL,
  `industry_coc` varchar(100) NOT NULL,
  PRIMARY KEY (`industry_ticker`,`industry_coc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Inserts for industry match*/
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Accident & Health Insurance','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Advanced Medical Equipment & Technology','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Advertising','Advertising');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Advertising Agencies','Advertising');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Aerospace & Defense','Aerospace/Defense');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Aerospace/Defense','Aerospace/Defense');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Aerospace/Defense - Major Diversified','Aerospace/Defense');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Aerospace/Defense Products & Services','Aerospace/Defense');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Agricultural & Farm Machinery','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Agricultural Chemicals','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Agricultural Products','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Air Delivery & Freight Services','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Air Freight & Logistics','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Air Services, Other','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Air Transport','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Airline','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Airlines','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Airport Services','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Alternative Carriers','Air Transport');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Aluminum','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Apparel','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Apparel & Accessories','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Apparel & Accessories Retailers','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Apparel Retail','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Apparel, Accessories & Luxury Goods','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Apparel/Accessories','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Appliance & Tool','Furn/Home Furnishings');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Application Software','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Asset Management','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Asset Management & Custody Banks','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Audio & Video Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto & Truck','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto & Truck Manufacturers','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto & Truck Parts','Auto Parts');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto Components','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto Dealerships','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto Manufacturers - Major','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto Parts','Auto Parts');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto Parts & Equipment','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto Vehicles, Parts & Service Retailers','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Auto, Truck & Motorcycle Parts','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Automobile Manufacturers','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Automotive Retail','Retail (Automotive)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Bank (Money Center)','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Banks','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Banks (Regional)','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Banks - Regional - US','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Basic Materials Wholesale','Chemical (Basic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverage (Alcoholic)','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverage (Soft)','Beverage (Soft)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverages','Beverage (Soft)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverages (Alcoholic)','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverages (Non-Alcoholic)','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverages - Soft Drinks','Beverage (Soft)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverages - Wineries & Distilleries','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Beverages - Wineries & Distillers','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Biotechnology','Drugs (Biotechnology)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Biotechnology & Drugs','Drugs (Biotechnology)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Biotechnology & Medical Research','Drugs (Biotechnology)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Brewers','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Broadcasting','Broadcasting');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Broadcasting & Cable TV','Broadcasting');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Broadcasting - TV','Broadcasting');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Brokerage & Investment Banking','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Building Materials','Building Materials');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Building Products','Building Materials');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Business & Consumer Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Business Equipment','Office Equipment & Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Business Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Business Software & Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Business Support Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Cable & Satellite','Cable TV');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Cable TV','Cable TV');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Capital Markets','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Casinos & Gaming','Hotel/Gaming');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Catalog & Mail Order Houses','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('CATV Systems','Cable TV');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Cement','Building Materials');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemical (Basic)','Chemical (Basic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemical (Diversified)','Chemical (Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemical (Specialty)','Chemical (Specialty)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemical Manufacturing','Chemical (Basic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemicals','Chemical (Basic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemicals - Major Diversified','Chemical (Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Chemicals - Plastics & Rubber','Chemical (Specialty)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Cigarettes','Tobacco');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Cleaning Products','Chemical (Basic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Closed End Funds','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Closed-End Fund - Equity','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Coal','Coal & Related Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Coal & Consumable Fuels','Coal & Related Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Coal & Related Energy','Coal & Related Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Commercial Printing','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Commercial Printing Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Commercial R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Commodity Chemicals','Chemical (Basic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Communication Equipment','Telecom. Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Communications & Networking','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Communications Equipment','Telecom. Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Communications Services','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer & Electronics Retail','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer Based Systems','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer Hardware','Computers/Peripherals');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer Networks','Computer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer Peripherals','Computers/Peripherals');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer Services','Computer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computer Storage Devices','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computers Wholesale','Retail (Distributors)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Computers/Peripherals','Computers/Peripherals');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Confectioners','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Conglomerates','Diversified');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Constr. & Agric. Machinery','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Constr. - Supplies & Fixtures','Construction Supplies');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction & Engineering','Engineering/Construction');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction & Farm Machinery & Heavy Trucks','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction - Raw Materials','Construction Supplies');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction Materials','Construction Supplies');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction Services','Engineering/Construction');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction Supplies','Construction Supplies');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Construction Supplies & Fixtures','Construction Supplies');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Consumer Electronics','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Consumer Finance','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Consumer Financial Services','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Consumer Lending','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Consumer Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Containers & Packaging','Packaging & Container');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Copper','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Corporate Financial Services','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Credit Services','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Crops','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Data Processing & Outsourced Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Data Storage Devices','Computers/Peripherals');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Department Stores','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diagnostic Substances','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diagnostics & Research','Heathcare Information and Technology');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Distillers & Vintners','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Distillers & Wineries','Beverage (Alcoholic)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Distributors','Retail (Distributors)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified','Diversified');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Banks','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Capital Markets','Total Market');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Chemicals','Chemical (Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Communication Services','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Computer Systems','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Consumer Services','Computer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Electronics','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Financial Services','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Industrials','Diversified');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Investments','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Machinery','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Metals & Mining','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Real Estate Activities','Real Estate (General/Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Support Services','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Diversified Utilities','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Delivery','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Manufacturers - Major','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Manufacturers - Other','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Manufacturers - Specialty & Generic','Drugs (Biotechnology)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Related Products','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Retail','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Retailers','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drug Stores','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drugs (Biotechnology)','Drugs (Biotechnology)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drugs (Pharmaceutical)','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Drugs - Generic','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Education','Education');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Education & Training Services','Education');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Education Services','Education');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electric Utilities','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electrical Components & Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electrical Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Components','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Equipment & Instruments','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Equipment & Parts','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Equipment, Instruments & Component','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Gaming & Multimedia','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Instr. & Controls','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronic Manufacturing Services','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronics (Consumer & Office)','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Electronics Wholesale','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Energy Equipment & Services','Coal & Related Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Engineering/Construction','Engineering/Construction');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Entertainment','Entertainment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Entertainment - Diversified','Entertainment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Entertainment Production','Entertainment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Environmental & Facilities Services','Environmental & Waste Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Environmental & Waste Services','Environmental & Waste Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Environmental Services & Equipment','Environmental & Waste Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Equity Real Estate Investment Trusts (R.E.I.T','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Fabricated Plastic & Rubber','Rubber& Tires');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Farm & Construction Machinery','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Farm Products','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Farming/Agriculture','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Fertilizers & Agricultural Chemicals','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Financial Exchanges & Data','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Financial Svcs. (Non-bank & Insurance)','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Fish/Livestock','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Fishing & Farming','Farming/Agriculture');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food & Staples Retailing','Retail (Grocery and Food)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food - Major Diversified','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food Distributors','Food Wholesalers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food Processing','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food Retail','Retail (Grocery and Food)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food Retail & Distribution','Retail (Grocery and Food)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food Wholesale','Food Wholesalers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Food Wholesalers','Food Wholesalers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Footwear','Shoe');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Foreign Money Center Banks','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Foreign Regional Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Forest & Wood Products','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Forest Products','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Forestry & Wood Products','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Furn/Home Furnishings','Furn/Home Furnishings');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Furniture & Fixtures','Furn/Home Furnishings');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Gaming Activities','Hotel/Gaming');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Gas Utilities','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('General Building Materials','Building Materials');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('General Contractors','Engineering/Construction');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('General Merchandise Stores','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Gold','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Gold & Silver','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Green & Renewable Energy','Green & Renewable Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Grocery Stores','Retail (Grocery and Food)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Ground Freight & Logistics','Transportation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Distributors','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Equipment','Healthcare Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Facilities','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Plans','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Providers & Services','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Services','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Supplies','Healthcare Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Care Technology','Heathcare Information and Technology');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Health Information Services','Heathcare Information and Technology');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Healthcare Facilities','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Healthcare Facilities & Services','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Healthcare Information Services','Heathcare Information and Technology');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Healthcare Products','Healthcare Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Healthcare Support Services','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Heathcare Information and Technology','Heathcare Information and Technology');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Heavy Construction','Engineering/Construction');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Heavy Electrical Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Heavy Machinery & Vehicles','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Holding Companies','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Home Entertainment Software','Software (Entertainment)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Home Furnishings','Furn/Home Furnishings');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Home Furnishings & Fixtures','Furn/Home Furnishings');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Home Improvement Products & Services Retailer','Homebuilding');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Home Improvement Retail','Homebuilding');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Homebuilding','Homebuilding');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Homefurnishing Retail','Furn/Home Furnishings');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hospitals','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hospitals/Healthcare Facilities','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hotel & Resort R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hotel/Gaming','Hotel/Gaming');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hotels & Motels','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hotels, Motels & Cruise Lines','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hotels, Resorts & Cruise Lines','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hotels, Restaurants & Leisure','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Household Appliances','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Household Products','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Housewares & Specialties','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Human Resource & Employment Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Hypermarkets & Super Centers','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Independent Oil & Gas','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Independent Power Producers','Power');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Independent Power Producers & Energy Traders','Power');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Conglomerates','Diversified');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Electrical Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Equipment & Components','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Equipment Wholesale','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Gases','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Machinery','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Machinery & Equipment','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial Metals & Minerals','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Industrial R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Information & Delivery Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Information Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Information Technology Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance (Accident & Health)','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance (General)','Insurance (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance (Life)','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance (Miscellaneous)','Insurance (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance (Prop. & Casualty)','Insurance (Prop/Cas.)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance (Prop/Cas.)','Insurance (Prop/Cas.)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance - Life','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Insurance Brokers','Insurance (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Integrated Mining','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Integrated Oil & Gas','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Integrated Telecommunication Services','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Integrated Telecommunications Services','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Internet & Direct Marketing Retail','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Internet Content & Information','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Internet Information Providers','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Internet Service Providers','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Internet Services','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Internet Software & Services','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investment Banking & Brokerage','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investment Banking & Brokerage Services','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investment Brokerage - National','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investment Management & Fund Operators','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investment Services','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investment Trusts','Brokerage & Investment Banking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Investments & Asset Management','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Iron & Steel','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('IT Consulting & Other Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('IT Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('IT Services & Consulting','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Jewelry & Silverware','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Jewelry Stores','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Leisure & Recreation','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Leisure Facilities','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Leisure Products','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Life & Health Insurance','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Life Insurance','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Life Sciences Tools & Services','Insurance (Life)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Lodging','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Long Distance Carriers','Transportation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Long-Term Care Facilities','Hospitals/Healthcare Facilities');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Lumber, Wood Production','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Machine Tools & Accessories','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Machinery','Machinery');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Major Drugs','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Major Integrated Oil & Gas','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Managed Health Care','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Management Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Marine','Shipbuilding & Marine');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Marine Port Services','Shipbuilding & Marine');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Marketing Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Materials','Building Materials');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Meat Products','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Media','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Media - Diversified','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Appliances & Equipment','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Care','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Equipment & Supplies','Healthcare Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Equipment, Supplies & Distribution','Healthcare Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Instruments & Supplies','Healthcare Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Laboratories & Research','Heathcare Information and Technology');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Medical Practitioners','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Metal & Glass Containers','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Metal Mining','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Metals & Mining','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Misc. Capital Goods','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Misc. Fabricated Products','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Misc. Financial Services','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Misc. Transportation','Transportation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Mobile Homes & RVs','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Money Center Banks','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Mortgage Investment','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Mortgage R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Motion Pictures','Entertainment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Motorcycle Manufacturers','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Movie Production, Theaters','Entertainment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Movies & Entertainment','Entertainment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Multi-line Insurance','Insurance (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Multi-Sector Holdings','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Multi-Utilities','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Multimedia & Graphics Software','Software (Entertainment)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Music & Video Stores','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Natural Gas Utilities','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Networking & Communication Devices','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Non-Metallic Mining','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Non-Paper Containers & Packaging','Packaging & Container');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Nonmetallic Mineral Mining','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Office Equipment','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Office Equipment & Services','Office Equipment & Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Office R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Office Services & Supplies','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Office Supplies','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas - Integrated','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Drilling','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Drilling & Exploration','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas E&P','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Equipment & Services','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Exploration & Production','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Exploration and Production','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Operations','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Refining & Marketing','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Refining and Marketing','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Storage & Transportation','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil & Gas Transportation Services','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil Related Services and Equipment','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil Well Services & Equipment','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil, Gas & Consumable Fuels','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Oil/Gas (Integrated)','Oil/Gas (Integrated)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Other Diversified Financial Services','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Other Specialty Retailers','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Packaged Foods & Meats','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Packaging & Container','Packaging & Container');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Packaging & Containers','Packaging & Container');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Paper & Paper Products','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Paper Packaging','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Paper Products','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Paper/Forest Products','Paper/Forest Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Personal & Household Prods.','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Personal Products','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Personal Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Pharmaceutical Retailers','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Pharmaceuticals','Drugs (Pharmaceutical)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Photographic Equipment & Supplies','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Photography','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Pollution & Treatment Controls','Green & Renewable Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Power','Power');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Precious Metals','Precious Metals');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Precious Metals & Minerals','Precious Metals');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Printed Circuit Boards','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Printing & Publishing','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Printing Services','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Processed & Packaged Goods','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Processing Systems & Products','Food Processing');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Professional Information Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Property & Casualty Insurance','Insurance (Prop/Cas.)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Property Management','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Publishing','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Publishing & Newspapers','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Publishing - Books','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Publishing - Newspapers','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Publishing - Periodicals','Publishing & Newspapers');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Railroads','Transportation (Railroads)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate','Real Estate (General/Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate (Development)','Real Estate (Development)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate (General/Diversified)','Real Estate (General/Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate (Operations & Services)','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate - General','Real Estate (General/Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate Development','Real Estate (Development)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate Development & Operations','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate Operating Companies','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate Operations','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Real Estate Services','Real Estate (Operations & Services)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Recreation','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Recreational Activities','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Recreational Goods, Other','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Recreational Products','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Recreational Vehicles','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional - Mid-Atlantic Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional - Midwest Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional - Northeast Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional - Pacific Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional - Southeast Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional - Southwest Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional Airlines','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Regional Banks','Banks (Regional)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Reinsurance','Reinsurance');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Diversified','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Hotel & Motel','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Hotel/Motel','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Industrial','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Office','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Residential','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('REIT - Retail','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Renewable Electricity','Green & Renewable Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Renewable Energy Equipment & Services','Green & Renewable Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Renewable Fuels','Green & Renewable Energy');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Rental & Leasing','Real Estate (General/Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Rental & Leasing Services','Real Estate (General/Diversified)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Research & Consulting Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Research Services','Information Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Residential Construction','Real Estate (Development)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Residential R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Resorts & Casinos','Hotel/Gaming');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Restaurant/Dining','Restaurant/Dining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Restaurants','Restaurant/Dining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Restaurants & Bars','Restaurant/Dining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Apparel)','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Automotive)','Retail (Automotive)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Catalog & Mail Order)','Retail (Online)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Department & Discount)','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Distributors)','Retail (Distributors)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Drugs)','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (General)','Retail (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Grocery and Food)','Retail (Grocery and Food)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Grocery)','Retail (Grocery and Food)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Home Improvement)','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Online)','Retail (Online)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Special Lines)','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Specialty)','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail (Technology)','Retail (Special Lines)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Retail R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Rubber & Plastics','Rubber& Tires');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Rubber& Tires','Rubber& Tires');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('S&Ls/Savings Banks','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Savings & Loans','Bank (Money Center)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Schools','Education');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Scientific & Technical Instr.','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Scientific & Technical Instruments','Electrical Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Security & Alarm Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Security & Protection Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Security Software & Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Security Systems & Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductor','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductor - Broad Line','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductor - Integrated Circuits','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductor - Specialized','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductor Equipment','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductor Equipment & Materials','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductors','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Semiconductors & Semiconductor Equipment','Semiconductor');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Shipbuilding & Marine','Shipbuilding & Marine');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Shipping','Transportation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Shoe','Shoe');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Silver','Metals & Mining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Small Tools & Accessories','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Soft Drinks','Beverage (Soft)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software','Software (Entertainment)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software & Programming','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software (Entertainment)','Software (Entertainment)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software (Internet)','Software (Internet)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software (System & Application)','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software - Application','Software (Entertainment)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Software - Infrastructure','Software (Entertainment)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialized Consumer Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialized Finance','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialized Health Services','Healthcare Support Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialized R.E.I.T.','R.E.I.T.');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialty Chemicals','Chemical (Specialty)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialty Eateries','Restaurant/Dining');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialty Finance','Financial Svcs. (Non-bank & Insurance)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialty Retail','Chemical (Specialty)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialty Retail, Other','Chemical (Specialty)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Specialty Stores','Chemical (Specialty)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Sporting Activities','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Sporting Goods','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Sporting Goods Stores','Recreation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Staffing & Outsourcing Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Steel','Steel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Steel & Iron','Steel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Surety & Title Insurance','Insurance (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Systems Software','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Technical & System Software','Software (System & Application)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Technical Services','Business & Consumer Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Technology Distributors','Retail (Distributors)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Technology Hardware, Storage & Peripherals','Electronics (Consumer & Office)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Telecom (Wireless)','Telecom (Wireless)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Telecom Services','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Telecom Services - Domestic','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Telecom Services - Foreign','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Telecom. Equipment','Telecom. Equipment');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Telecom. Services','Telecom. Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Textile - Apparel Clothing','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Textile - Apparel Footwear & Accessories','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Textile Industrial','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Textiles','Apparel');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Textiles & Leather Goods','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Textiles - Non Apparel','Household Products');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Thrifts & Mortgage Finance','Investments & Asset Management');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Tires','Rubber& Tires');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Tires & Rubber','Rubber& Tires');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Tobacco','Tobacco');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Tobacco Products, Other','Tobacco');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Total Market','Total Market');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Trading Companies & Distributors','Retail (Distributors)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Transportation','Transportation');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Transportation (Railroads)','Transportation (Railroads)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Trucking','Trucking');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Trucks & Other Vehicles','Auto & Truck');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Utilities - Diversified','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Utility (General)','Utility (General)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Utility (Water)','Utility (Water)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Waste Management','Environmental & Waste Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Waste Management Services','Environmental & Waste Services');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Water Transportation','Utility (Water)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Water Utilities','Utility (Water)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Wholesale, Other','Retail (Distributors)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Wireless Communications','Telecom (Wireless)');
INSERT INTO `industry_match` (`industry_ticker`,`industry_coc`) VALUES ('Wireless Telecommunication Services','Telecom. Services');

/* Inserts for industry coc */
TRUNCATE `industry_coc`;

INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Advertising',1.360000000000000,0.102100000000000,0.040500000000000,0.072000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Aerospace/Defense',1.070000000000000,0.085600000000000,0.037000000000000,0.073600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Air Transport',1.120000000000000,0.088300000000000,0.035000000000000,0.060600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Apparel',0.880000000000000,0.074600000000000,0.037000000000000,0.061200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Auto & Truck',0.850000000000000,0.072600000000000,0.035000000000000,0.041600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Auto Parts',1.120000000000000,0.088400000000000,0.037000000000000,0.071100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Bank (Money Center)',0.860000000000000,0.073400000000000,0.035000000000000,0.039200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Banks (Regional)',0.470000000000000,0.051400000000000,0.030500000000000,0.038900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Beverage (Alcoholic)',0.790000000000000,0.069600000000000,0.037000000000000,0.058900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Beverage (Soft)',0.910000000000000,0.076400000000000,0.037000000000000,0.065700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Broadcasting',1.220000000000000,0.093900000000000,0.037000000000000,0.058800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Brokerage & Investment Banking',1.080000000000000,0.085800000000000,0.037000000000000,0.041300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Building Materials',1.010000000000000,0.081800000000000,0.035000000000000,0.068900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Business & Consumer Services',1.070000000000000,0.085400000000000,0.037000000000000,0.069000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Cable TV',1.120000000000000,0.088000000000000,0.035000000000000,0.065900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Chemical (Basic)',1.000000000000000,0.081500000000000,0.037000000000000,0.059600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Chemical (Diversified)',1.520000000000000,0.110900000000000,0.037000000000000,0.087700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Chemical (Specialty)',1.200000000000000,0.092700000000000,0.037000000000000,0.076400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Coal & Related Energy',1.360000000000000,0.102100000000000,0.040500000000000,0.056900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Computer Services',0.990000000000000,0.080600000000000,0.037000000000000,0.067700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Computers/Peripherals',1.060000000000000,0.084600000000000,0.037000000000000,0.074300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Construction Supplies',1.310000000000000,0.099300000000000,0.035000000000000,0.075900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Diversified',0.760000000000000,0.068000000000000,0.030500000000000,0.054900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Drugs (Biotechnology)',1.400000000000000,0.104300000000000,0.052000000000000,0.092400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Drugs (Pharmaceutical)',1.020000000000000,0.082300000000000,0.040500000000000,0.074900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Education',1.230000000000000,0.094200000000000,0.037000000000000,0.076200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Electrical Equipment',1.140000000000000,0.089600000000000,0.037000000000000,0.078700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Electronics (Consumer & Office)',1.080000000000000,0.086100000000000,0.040500000000000,0.076100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Electronics (General)',0.860000000000000,0.073700000000000,0.037000000000000,0.065900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Engineering/Construction',1.180000000000000,0.091700000000000,0.037000000000000,0.074700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Entertainment',1.200000000000000,0.092900000000000,0.037000000000000,0.076300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Environmental & Waste Services',0.850000000000000,0.073000000000000,0.037000000000000,0.058700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Farming/Agriculture',0.920000000000000,0.076800000000000,0.037000000000000,0.056300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Financial Svcs. (Non-bank & Insurance)',0.650000000000000,0.061700000000000,0.035000000000000,0.024300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Food Processing',0.750000000000000,0.067400000000000,0.035000000000000,0.057600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Food Wholesalers',1.200000000000000,0.093000000000000,0.037000000000000,0.074100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Furn/Home Furnishings',0.840000000000000,0.072000000000000,0.037000000000000,0.060800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Green & Renewable Energy',1.140000000000000,0.089400000000000,0.037000000000000,0.046700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Healthcare Products',1.040000000000000,0.083500000000000,0.037000000000000,0.074100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Healthcare Support Services',0.940000000000000,0.077900000000000,0.037000000000000,0.064400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Heathcare Information and Technology',0.950000000000000,0.078600000000000,0.037000000000000,0.068900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Homebuilding',1.080000000000000,0.085800000000000,0.035000000000000,0.060000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Hospitals/Healthcare Facilities',1.100000000000000,0.087000000000000,0.037000000000000,0.046100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Hotel/Gaming',0.960000000000000,0.079200000000000,0.035000000000000,0.058500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Household Products',0.800000000000000,0.069800000000000,0.037000000000000,0.061500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Information Services',0.980000000000000,0.080300000000000,0.035000000000000,0.070300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Insurance (General)',0.900000000000000,0.076000000000000,0.035000000000000,0.060600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Insurance (Life)',1.030000000000000,0.083400000000000,0.035000000000000,0.057400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Insurance (Prop/Cas.)',0.830000000000000,0.071700000000000,0.035000000000000,0.059700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Investments & Asset Management',0.900000000000000,0.075500000000000,0.035000000000000,0.054700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Machinery',1.060000000000000,0.084900000000000,0.035000000000000,0.073500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Metals & Mining',1.300000000000000,0.098700000000000,0.052000000000000,0.075600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Office Equipment & Services',1.490000000000000,0.109300000000000,0.035000000000000,0.078200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Oil/Gas (Integrated)',1.080000000000000,0.086000000000000,0.037000000000000,0.076800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Oil/Gas (Production and Exploration)',1.380000000000000,0.102900000000000,0.052000000000000,0.080000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Oil/Gas Distribution',1.200000000000000,0.092500000000000,0.037000000000000,0.061900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Oilfield Svcs/Equip.',1.370000000000000,0.102200000000000,0.037000000000000,0.082500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Packaging & Container',0.840000000000000,0.072200000000000,0.035000000000000,0.053800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Paper/Forest Products',1.120000000000000,0.088100000000000,0.035000000000000,0.066000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Power',0.540000000000000,0.055500000000000,0.030500000000000,0.038100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Precious Metals',1.250000000000000,0.095700000000000,0.052000000000000,0.083200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Publishing & Newspapers',1.320000000000000,0.099600000000000,0.037000000000000,0.071500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('R.E.I.T.',0.720000000000000,0.065700000000000,0.030500000000000,0.044700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Real Estate (Development)',0.680000000000000,0.063400000000000,0.035000000000000,0.047400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Real Estate (General/Diversified)',1.270000000000000,0.096800000000000,0.030500000000000,0.081400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Real Estate (Operations & Services)',0.990000000000000,0.080900000000000,0.037000000000000,0.055400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Recreation',0.920000000000000,0.076900000000000,0.037000000000000,0.063900000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Reinsurance',0.750000000000000,0.067000000000000,0.030500000000000,0.055100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Restaurant/Dining',0.770000000000000,0.068200000000000,0.035000000000000,0.056000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (Automotive)',0.910000000000000,0.076500000000000,0.035000000000000,0.055700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (Building Supply)',1.300000000000000,0.098400000000000,0.035000000000000,0.084500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (Distributors)',1.100000000000000,0.087400000000000,0.037000000000000,0.063700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (General)',1.050000000000000,0.084200000000000,0.037000000000000,0.066600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (Grocery and Food)',0.690000000000000,0.063800000000000,0.035000000000000,0.046600000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (Online)',1.230000000000000,0.094300000000000,0.037000000000000,0.088000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Retail (Special Lines)',1.020000000000000,0.082700000000000,0.037000000000000,0.062000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Rubber& Tires',1.350000000000000,0.101100000000000,0.037000000000000,0.068000000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Semiconductor',1.200000000000000,0.092500000000000,0.037000000000000,0.083800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Semiconductor Equip',1.100000000000000,0.086900000000000,0.035000000000000,0.077700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Shipbuilding & Marine',1.200000000000000,0.092900000000000,0.040500000000000,0.070500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Shoe',0.850000000000000,0.073000000000000,0.035000000000000,0.068100000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Software (Entertainment)',0.980000000000000,0.080300000000000,0.037000000000000,0.072800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Software (Internet)',1.130000000000000,0.089000000000000,0.037000000000000,0.086300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Software (System & Application)',1.130000000000000,0.088600000000000,0.037000000000000,0.076800000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Steel',1.600000000000000,0.115500000000000,0.037000000000000,0.085300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Telecom (Wireless)',1.120000000000000,0.088000000000000,0.035000000000000,0.052200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Telecom. Equipment',0.990000000000000,0.080800000000000,0.037000000000000,0.069200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Telecom. Services',1.040000000000000,0.083800000000000,0.037000000000000,0.059300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Tobacco',1.280000000000000,0.097300000000000,0.037000000000000,0.086300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Total Market',1.000000000000000,0.081500000000000,0.037000000000000,0.057500000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Total Market (without financials)',1.080000000000000,0.085900000000000,0.037000000000000,0.069200000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Transportation',1.010000000000000,0.082200000000000,0.035000000000000,0.067400000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Transportation (Railroads)',0.790000000000000,0.069200000000000,0.035000000000000,0.058700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Trucking',1.210000000000000,0.093100000000000,0.037000000000000,0.059300000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Utility (General)',0.380000000000000,0.045900000000000,0.030500000000000,0.034700000000000);
INSERT INTO `industry_coc` (`industry`,`beta`,`cost_equity`,`cost_debt`,`cost_capital`) VALUES ('Utility (Water)',0.650000000000000,0.061400000000000,0.035000000000000,0.049200000000000);


