CREATE TABLE IF NOT EXISTS `tickers_eod_valuation` (
  `ticker_id` bigint(20) NOT NULL,
  `dcf_eps` decimal(30,15) DEFAULT NULL COMMENT 'DCF Fair Value using EPS|Earnings based multi-stage Discounted Cash Flow. CAUTION: Fair value calculation uses automatic numbers and does not include required human adjustments. Use at own risk in a screener.|osvcurrency:2|DCF EPS',
  `dcf_fcf` decimal(30,15) DEFAULT NULL COMMENT 'DCF Fair Value using FCF|Free Cash Flow based multi-stage Discounted Cash Flow. CAUTION: Fair value calculation uses automatic numbers and does not include required human adjustments. Use at own risk in a screener.|osvcurrency:2|DCF FCF',
  `dcf_oe` decimal(30,15) DEFAULT NULL COMMENT 'DCF Fair Value using Owner Earnings OE|Owner Earnings based multi-stage Discounted Cash Flow. CAUTION: Fair value calculation uses automatic numbers and does not include required human adjustments. Use at own risk in a screener.|osvcurrency:2|DCF OE',
  `graham` decimal(30,15) DEFAULT NULL COMMENT 'Graham Formula Fair Value|Fair value using Ben Graham''s Formula as defined in The Intelligent Investor. A high end estimate of fair value. Optimistic as it uses raw growth numbers. CAUTION: Fair value calculation uses automatic numbers and does not include required human adjustments. Use at own risk in a screener.|osvcurrency:2|Graham',
  `ebit` decimal(30,15) DEFAULT NULL COMMENT 'EBIT Multiples Fair Value Normal Case|The normal case using 3 year normalized EBIT margins. CAUTION: Fair value calculation uses automatic numbers and does not include required human adjustments. Use at own risk in a screener.|osvcurrency:2|EBIT FV',
  `p_dcf_eps` decimal(30,15) DEFAULT NULL COMMENT 'Price to DCF (EPS Based)|Price to Fair Value ratio for Earnings based DCF. Ratio < 1 means it is undervalued. Lower the cheaper. CAUTION: Valuations change with a single input. Use at own risk.|osvnumber:2:true|P/DCF-EPS',
  `p_dcf_fcf` decimal(30,15) DEFAULT NULL COMMENT 'Price to DCF (FCF Based)|Price to Fair Value ratio for FCF based DCF. Ratio < 1 means it is undervalued. Lower the cheaper. CAUTION: Valuations change with a single input. Use at own risk.|osvnumber:2:true|P/DCF-FCF',
  `p_dcf_oe` decimal(30,15) DEFAULT NULL COMMENT 'Price to DCF (Owner Earnings Based)|Price to Fair Value ratio for Owner Earnings based DCF. Ratio < 1 means it is undervalued. Lower the cheaper. CAUTION: Valuations change with a single input. Use at own risk.|osvnumber:2:true|P/DCF-OE',
  `p_graham` decimal(30,15) DEFAULT NULL COMMENT 'Price to Graham|Price to Fair Value ratio for Graham''s Formula. Ratio < 1 means it is undervalued. Lower the cheaper. CAUTION: Valuations change with a single input. Use at own risk.|osvnumber:2:true|P/Graham',
  `p_ebit` decimal(30,15) DEFAULT NULL COMMENT 'Price to EBIT Fair Value (Normal Case)|Price to Fair Value ratio for the 3 yr Normalized EBIT Multiples. Ratio < 1 means it is undervalued. Lower the cheaper. CAUTION: Valuations change with a single input. Use at own risk.|osvnumber:2:true|P/EBIT-FV',
  `mos_dcf_eps` decimal(30,15) DEFAULT NULL COMMENT 'DCF Margin of Safety (EPS Based MOS)|Margin of Safety % for Earnings based DCF|osvpercent:2:true|MOS DCF-EPS',
  `mos_dcf_fcf` decimal(30,15) DEFAULT NULL COMMENT 'DCF Margin of Safety (FCF Based MOS)|Margin of Safety % for FCF based DCF|osvpercent:2:true|MOS DCF-FCF',
  `mos_dcf_oe` decimal(30,15) DEFAULT NULL COMMENT 'DCF Margin of Safety (OE Based MOS)|Margin of Safety % for Owner Earnings based DCF|osvpercent:2:true|MOS DCF-OE',
  `mos_graham` decimal(30,15) DEFAULT NULL COMMENT 'Graham Margin of Safety|Margin of Safety % for Ben Graham fair value|osvpercent:2:true|MOS Graham',
  `mos_ebit` decimal(30,15) DEFAULT NULL COMMENT 'EBIT Fair Value Margin of Safety|Margin of Safety % for 3 yr Normalized EBIT Multiples fair value|osvpercent:2:true|MOS EBIT FV',
  PRIMARY KEY (`ticker_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE  `screener_filter_fields` CHANGE  `field_table_field`  `field_table_field` VARCHAR( 150 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
CHANGE  `field_name`  `field_name` VARCHAR( 150 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;

ALTER TABLE  `screener_filter_fields2` CHANGE  `field_table_field`  `field_table_field` VARCHAR( 150 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
CHANGE  `field_name`  `field_name` VARCHAR( 150 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;

GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE TEMPORARY TABLES ON jjun0366_frontend.* TO 'wsuser'@'localhost';
FLUSH PRIVILEGES;

TRUNCATE TABLE `screener_field_fields`;

INSERT INTO `screener_field_fields` (`field_id`, `field_name`, `field_group`, `field_order`, `field_display_order`, `field_display_group`) VALUES
(6, 'exchange', 0, 'NONE', 1, 1),
(7, 'sector', 0, 'NONE', 2, 1),
(8, 'industry', 0, 'NONE', 3, 1),
(9, '52WeekHighValue', 0, 'NONE', 4, 1),
(10, '52WeekLowValue', 0, 'NONE', 5, 1),
(11, 'LastTradePriceOnly', 0, 'NONE', 6, 1),
(12, 'ChangeInPercent', 0, 'DESC', 7, 1),
(13, 'MarketCapIntraday', 0, 'NONE', 8, 1),
(14, 'EnterpriseValue', 0, 'NONE', 9, 1),
(15, 'ForwardAnnualDividendYield', 0, 'NONE', 10, 1),
(16, 'PayoutRatio', 0, 'NONE', 11, 1),
(17, '5YearAverageDividendYield', 0, 'NONE', 12, 1),
(18, 'PercentageHeldByInsiders', 0, 'NONE', 13, 1),
(19, 'PercentageHeldByInstitutions', 0, 'NONE', 14, 1),
(20, 'ShortPercentageOfFloat', 0, 'NONE', 15, 1),
(21, 'ShortRatio', 0, 'NONE', 16, 1),
(22, 'DilutedEPSTTM', 0, 'NONE', 17, 1),
(23, 'GrossMarginPercent', 3, 'NONE', 18, 1),
(24, 'OperatingMarginPercent', 3, 'NONE', 19, 1),
(25, 'NetMarginPercent', 3, 'NONE', 20, 1),
(28, 'AS_grade', 3, 'NONE', 0, 2),
(29, 'QT', 3, 'DESC', 2, 2),
(30, 'VT', 3, 'DESC', 3, 2),
(31, 'GT', 3, 'DESC', 4, 2),
(32, 'pioTotal', 3, 'DESC', 5, 2),
(33, 'FCF_S', 3, 'DESC', 6, 2),
(34, 'CROIC', 3, 'NONE', 7, 2),
(35, 'EV_EBIT', 3, 'NONE', 8, 2),
(36, 'P_FCF', 3, 'NONE', 9, 2),
(37, 'P_BV', 3, 'NONE', 10, 2),
(38, 'Sales5YYCGrPerc', 3, 'NONE', 12, 2),
(39, 'GPA', 3, 'NONE', 13, 2),
(40, 'RevenuePctGrowthTTM', 0, 'NONE', 14, 2),
(42, 'P_E', 3, 'NONE', 1, 3),
(43, 'EV_EBITDA', 3, 'NONE', 2, 3),
(44, 'EV_EBIT', 3, 'NONE', 3, 3),
(45, 'P_S', 3, 'NONE', 4, 3),
(46, 'P_BV', 3, 'NONE', 5, 3),
(47, 'P_Tang_BV', 3, 'NONE', 6, 3),
(48, 'P_FCF', 3, 'NONE', 7, 3),
(49, 'P_OwnerEarnings', 3, 'NONE', 8, 3),
(50, 'FCF_S', 3, 'NONE', 19, 3),
(51, 'FCFYield', 3, 'NONE', 20, 3),
(52, 'MagicFormulaEarningsYield', 3, 'NONE', 21, 3),
(53, 'ROE', 3, 'NONE', 22, 3),
(54, 'ROA', 3, 'NONE', 23, 3),
(55, 'ROIC', 3, 'NONE', 24, 3),
(56, 'CROIC', 3, 'NONE', 25, 3),
(57, 'GPA', 3, 'NONE', 26, 3),
(58, 'BooktoMarket', 3, 'NONE', 27, 3),
(61, 'ES_ActualEarningsPerShareForMostRecentQuarter', 0, 'NONE', 2, 4),
(62, 'ES_MostRecentQuarterSurprisePercent', 0, 'NONE', 3, 4),
(64, 'EE_CurrentQuarterMean', 0, 'NONE', 5, 4),
(66, 'EE_NextQuarterCurrentMean', 0, 'NONE', 7, 4),
(68, 'EE_CurrentFiscalYearMean', 0, 'NONE', 9, 4),
(70, 'EE_NextFiscalYearCurrentMean', 0, 'NONE', 11, 4),
(71, 'EE_LongTermGrowthCurrentMean', 0, 'NONE', 12, 4),
(72, 'EGR_CompanyLast5YearActualPercentageGrowth', 0, 'NONE', 13, 4),
(73, 'EGR_IndustryLast5YearActualPercentGrowth', 0, 'NONE', 14, 4),
(74, 'EGR_IndustryLongTermGrowthRate', 0, 'NONE', 15, 4),
(75, 'EGR_IndustryNextFiscalYearPERatio', 0, 'NONE', 16, 4),
(76, 'SA_MeanEstimateSectorLongTermGrowth', 0, 'NONE', 17, 4),
(79, 'EGR_SP500Last5YearActualPercentGrowth', 0, 'NONE', 20, 4),
(81, 'QuickRatio', 3, 'DESC', 1, 5),
(82, 'CurrentRatio', 3, 'NONE', 2, 5),
(83, 'TotalDebt_EquityRatio', 3, 'NONE', 3, 5),
(84, 'LongTermDebt_EquityRatio', 3, 'NONE', 4, 5),
(85, 'ShortTermDebt_EquityRatio', 3, 'NONE', 5, 5),
(87, 'AssetTurnover', 3, 'DESC', 1, 6),
(88, 'CashPercofRevenue', 3, 'NONE', 2, 6),
(89, 'ReceivablesPercofRevenue', 3, 'NONE', 3, 6),
(90, 'SG_APercofRevenue', 3, 'NONE', 4, 6),
(91, 'R_DPercofRevenue', 3, 'NONE', 5, 6),
(93, 'DaysSalesOutstanding', 3, 'NONE', 1, 7),
(94, 'DaysInventoryOutstanding', 3, 'NONE', 2, 7),
(95, 'DaysPayableOutstanding', 3, 'NONE', 3, 7),
(96, 'CashConversionCycle', 3, 'DESC', 4, 7),
(97, 'ReceivablesTurnover', 3, 'NONE', 5, 7),
(98, 'InventoryTurnover', 3, 'NONE', 6, 7),
(99, 'AverageAgeofInventory', 3, 'NONE', 7, 7),
(100, 'IntangiblesPercofBookValue', 3, 'NONE', 8, 7),
(101, 'InventoryPercofRevenue', 3, 'NONE', 9, 7),
(103, 'LT_DebtasPercofInvestedCapital', 3, 'DESC', 1, 8),
(104, 'ST_DebtasPercofInvestedCapital', 3, 'NONE', 2, 8),
(105, 'LT_DebtasPercofTotalDebt', 3, 'NONE', 3, 8),
(106, 'ST_DebtasPercofTotalDebt', 3, 'NONE', 4, 8),
(107, 'TotalDebtPercofTotalAssets', 3, 'NONE', 5, 8),
(108, 'WorkingCapitalPercofPrice', 3, 'NONE', 6, 8),
(110, 'pioTotal', 3, 'DESC', 1, 9),
(111, 'AltmanZNormal', 8, 'DESC', 2, 9),
(112, 'AltmanZRevised', 8, 'NONE', 3, 9),
(113, 'BM5', 3, 'NONE', 4, 9),
(114, 'BM8', 3, 'NONE', 5, 9),
(162, 'TotalRevenue', 4, 'DESC', 1, 10),
(163, 'operatingProfit', 4, 'NONE', 2, 10),
(164, 'netIncomeTotal', 4, 'NONE', 3, 10),
(165, 'eps', 4, 'NONE', 4, 10),
(166, 'dilutedSharesOutstanding', 4, 'NONE', 5, 10),
(167, 'TotalCurrentAssets', 4, 'NONE', 6, 10),
(168, 'TotalLongtermAssets', 4, 'NONE', 7, 10),
(169, 'TotalAssets', 4, 'NONE', 8, 10),
(170, 'TotalCurrentLiabilities', 4, 'NONE', 9, 10),
(171, 'TotalLongtermLiabilities', 4, 'NONE', 10, 10),
(172, 'TotalLiabilities', 4, 'NONE', 11, 10),
(173, 'TotalStockholdersEquity', 4, 'NONE', 12, 10),
(174, 'CashfromOperatingActivities', 4, 'NONE', 13, 10),
(175, 'CapitalExpenditures', 4, 'NONE', 14, 10),
(176, 'FreeCashFlow', 4, 'NONE', 15, 10),
(177, 'AS', 3, 'DESC', 1, 2),
(178, 'p_dcf_eps', 0, 'NONE', 9, 3),
(179, 'p_dcf_fcf', 0, 'NONE', 10, 3),
(180, 'p_dcf_oe', 0, 'NONE', 11, 3),
(181, 'p_graham', 0, 'NONE', 12, 3),
(182, 'p_ebit', 0, 'NONE', 13, 3),
(183, 'mos_dcf_eps', 0, 'NONE', 14, 3),
(184, 'mos_dcf_fcf', 0, 'NONE', 15, 3),
(185, 'mos_dcf_oe', 0, 'NONE', 16, 3),
(186, 'mos_graham', 0, 'NONE', 17, 3),
(187, 'mos_ebit', 0, 'NONE', 18, 3);

