DROP TABLE IF EXISTS `reports_balanceconsolidated_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_balanceconsolidated_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `CommitmentsContingencies` decimal(30,15) DEFAULT NULL,
  `CommonStock` decimal(30,15) DEFAULT NULL,
  `DeferredCharges` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesCurrent` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesLongterm` decimal(30,15) DEFAULT NULL,
  `AccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccruedInterest` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapital` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapitalPreferredStock` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalents` decimal(30,15) DEFAULT NULL,
  `CashCashEquivalentsandShorttermInvestments` decimal(30,15) DEFAULT NULL,
  `Goodwill` decimal(30,15) DEFAULT NULL,
  `IntangibleAssets` decimal(30,15) DEFAULT NULL,
  `InventoriesNet` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredIncomeTaxLiabilities` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `LongtermInvestments` decimal(30,15) DEFAULT NULL,
  `MinorityInterest` decimal(30,15) DEFAULT NULL,
  `OtherAccumulatedComprehensiveIncome` decimal(30,15) DEFAULT NULL,
  `OtherAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `OtherEquity` decimal(30,15) DEFAULT NULL,
  `OtherInvestments` decimal(30,15) DEFAULT NULL,
  `OtherLiabilities` decimal(30,15) DEFAULT NULL,
  `PartnersCapital` decimal(30,15) DEFAULT NULL,
  `PensionPostretirementObligation` decimal(30,15) DEFAULT NULL,
  `PreferredStock` decimal(30,15) DEFAULT NULL,
  `PrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `PropertyPlantEquipmentNet` decimal(30,15) DEFAULT NULL,
  `RestrictedCash` decimal(30,15) DEFAULT NULL,
  `RetainedEarnings` decimal(30,15) DEFAULT NULL,
  `TemporaryEquity` decimal(30,15) DEFAULT NULL,
  `TotalAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLongtermDebt` decimal(30,15) DEFAULT NULL,
  `TotalReceivablesNet` decimal(30,15) DEFAULT NULL,
  `TotalShorttermDebt` decimal(30,15) DEFAULT NULL,
  `TotalStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `TreasuryStock` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balanceconsolidated_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_balanceconsolidated_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `CommitmentsContingencies` decimal(30,15) DEFAULT NULL,
  `CommonStock` decimal(30,15) DEFAULT NULL,
  `DeferredCharges` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesCurrent` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesLongterm` decimal(30,15) DEFAULT NULL,
  `AccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccruedInterest` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapital` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapitalPreferredStock` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalents` decimal(30,15) DEFAULT NULL,
  `CashCashEquivalentsandShorttermInvestments` decimal(30,15) DEFAULT NULL,
  `Goodwill` decimal(30,15) DEFAULT NULL,
  `IntangibleAssets` decimal(30,15) DEFAULT NULL,
  `InventoriesNet` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredIncomeTaxLiabilities` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `LongtermInvestments` decimal(30,15) DEFAULT NULL,
  `MinorityInterest` decimal(30,15) DEFAULT NULL,
  `OtherAccumulatedComprehensiveIncome` decimal(30,15) DEFAULT NULL,
  `OtherAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `OtherEquity` decimal(30,15) DEFAULT NULL,
  `OtherInvestments` decimal(30,15) DEFAULT NULL,
  `OtherLiabilities` decimal(30,15) DEFAULT NULL,
  `PartnersCapital` decimal(30,15) DEFAULT NULL,
  `PensionPostretirementObligation` decimal(30,15) DEFAULT NULL,
  `PreferredStock` decimal(30,15) DEFAULT NULL,
  `PrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `PropertyPlantEquipmentNet` decimal(30,15) DEFAULT NULL,
  `RestrictedCash` decimal(30,15) DEFAULT NULL,
  `RetainedEarnings` decimal(30,15) DEFAULT NULL,
  `TemporaryEquity` decimal(30,15) DEFAULT NULL,
  `TotalAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLongtermDebt` decimal(30,15) DEFAULT NULL,
  `TotalReceivablesNet` decimal(30,15) DEFAULT NULL,
  `TotalShorttermDebt` decimal(30,15) DEFAULT NULL,
  `TotalStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `TreasuryStock` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balanceconsolidated_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_balanceconsolidated_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `CommitmentsContingencies` decimal(30,15) DEFAULT NULL,
  `CommonStock` decimal(30,15) DEFAULT NULL,
  `DeferredCharges` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesCurrent` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesLongterm` decimal(30,15) DEFAULT NULL,
  `AccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccruedInterest` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapital` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapitalPreferredStock` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalents` decimal(30,15) DEFAULT NULL,
  `CashCashEquivalentsandShorttermInvestments` decimal(30,15) DEFAULT NULL,
  `Goodwill` decimal(30,15) DEFAULT NULL,
  `IntangibleAssets` decimal(30,15) DEFAULT NULL,
  `InventoriesNet` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredIncomeTaxLiabilities` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `LongtermInvestments` decimal(30,15) DEFAULT NULL,
  `MinorityInterest` decimal(30,15) DEFAULT NULL,
  `OtherAccumulatedComprehensiveIncome` decimal(30,15) DEFAULT NULL,
  `OtherAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `OtherEquity` decimal(30,15) DEFAULT NULL,
  `OtherInvestments` decimal(30,15) DEFAULT NULL,
  `OtherLiabilities` decimal(30,15) DEFAULT NULL,
  `PartnersCapital` decimal(30,15) DEFAULT NULL,
  `PensionPostretirementObligation` decimal(30,15) DEFAULT NULL,
  `PreferredStock` decimal(30,15) DEFAULT NULL,
  `PrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `PropertyPlantEquipmentNet` decimal(30,15) DEFAULT NULL,
  `RestrictedCash` decimal(30,15) DEFAULT NULL,
  `RetainedEarnings` decimal(30,15) DEFAULT NULL,
  `TemporaryEquity` decimal(30,15) DEFAULT NULL,
  `TotalAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLongtermDebt` decimal(30,15) DEFAULT NULL,
  `TotalReceivablesNet` decimal(30,15) DEFAULT NULL,
  `TotalShorttermDebt` decimal(30,15) DEFAULT NULL,
  `TotalStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `TreasuryStock` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balanceconsolidated_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_balanceconsolidated_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `CommitmentsContingencies` decimal(30,15) DEFAULT NULL,
  `CommonStock` decimal(30,15) DEFAULT NULL,
  `DeferredCharges` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesCurrent` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxesLongterm` decimal(30,15) DEFAULT NULL,
  `AccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccruedInterest` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapital` decimal(30,15) DEFAULT NULL,
  `AdditionalPaidinCapitalPreferredStock` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalents` decimal(30,15) DEFAULT NULL,
  `CashCashEquivalentsandShorttermInvestments` decimal(30,15) DEFAULT NULL,
  `Goodwill` decimal(30,15) DEFAULT NULL,
  `IntangibleAssets` decimal(30,15) DEFAULT NULL,
  `InventoriesNet` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredIncomeTaxLiabilities` decimal(30,15) DEFAULT NULL,
  `LongtermDeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `LongtermInvestments` decimal(30,15) DEFAULT NULL,
  `MinorityInterest` decimal(30,15) DEFAULT NULL,
  `OtherAccumulatedComprehensiveIncome` decimal(30,15) DEFAULT NULL,
  `OtherAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `OtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `OtherEquity` decimal(30,15) DEFAULT NULL,
  `OtherInvestments` decimal(30,15) DEFAULT NULL,
  `OtherLiabilities` decimal(30,15) DEFAULT NULL,
  `PartnersCapital` decimal(30,15) DEFAULT NULL,
  `PensionPostretirementObligation` decimal(30,15) DEFAULT NULL,
  `PreferredStock` decimal(30,15) DEFAULT NULL,
  `PrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `PropertyPlantEquipmentNet` decimal(30,15) DEFAULT NULL,
  `RestrictedCash` decimal(30,15) DEFAULT NULL,
  `RetainedEarnings` decimal(30,15) DEFAULT NULL,
  `TemporaryEquity` decimal(30,15) DEFAULT NULL,
  `TotalAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentAssets` decimal(30,15) DEFAULT NULL,
  `TotalCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalLongtermDebt` decimal(30,15) DEFAULT NULL,
  `TotalReceivablesNet` decimal(30,15) DEFAULT NULL,
  `TotalShorttermDebt` decimal(30,15) DEFAULT NULL,
  `TotalStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `TreasuryStock` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balancefull_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_balancefull_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `TotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFQ` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFY` decimal(30,15) DEFAULT NULL,
  `CurrentPortionofLongtermDebt` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxLiabilitiesShortterm` decimal(30,15) DEFAULT NULL,
  `DeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `AccountsNotesReceivableNet` decimal(30,15) DEFAULT NULL,
  `AccountsPayable` decimal(30,15) DEFAULT NULL,
  `AccountsReceivableTradeNet` decimal(30,15) DEFAULT NULL,
  `AccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccumulatedDepreciation` decimal(30,15) DEFAULT NULL,
  `AmountsDuetoRelatedPartiesShortterm` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `IncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `LiabilitiesStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebt` decimal(30,15) DEFAULT NULL,
  `NotesPayable` decimal(30,15) DEFAULT NULL,
  `OperatingLeases` decimal(30,15) DEFAULT NULL,
  `OtherAccountsNotesReceivable` decimal(30,15) DEFAULT NULL,
  `OtherAccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `OtherBorrowings` decimal(30,15) DEFAULT NULL,
  `OtherReceivables` decimal(30,15) DEFAULT NULL,
  `PropertyandEquipmentGross` decimal(30,15) DEFAULT NULL,
  `TotalLongtermAssets` decimal(30,15) DEFAULT NULL,
  `TotalLongtermLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalSharesOutstanding` decimal(30,15) DEFAULT NULL,
  `ShorttermInvestments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balancefull_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_balancefull_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `TotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFQ` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFY` decimal(30,15) DEFAULT NULL,
  `CurrentPortionofLongtermDebt` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxLiabilitiesShortterm` decimal(30,15) DEFAULT NULL,
  `DeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `AccountsNotesReceivableNet` decimal(30,15) DEFAULT NULL,
  `AccountsPayable` decimal(30,15) DEFAULT NULL,
  `AccountsReceivableTradeNet` decimal(30,15) DEFAULT NULL,
  `AccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccumulatedDepreciation` decimal(30,15) DEFAULT NULL,
  `AmountsDuetoRelatedPartiesShortterm` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `IncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `LiabilitiesStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebt` decimal(30,15) DEFAULT NULL,
  `NotesPayable` decimal(30,15) DEFAULT NULL,
  `OperatingLeases` decimal(30,15) DEFAULT NULL,
  `OtherAccountsNotesReceivable` decimal(30,15) DEFAULT NULL,
  `OtherAccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `OtherBorrowings` decimal(30,15) DEFAULT NULL,
  `OtherReceivables` decimal(30,15) DEFAULT NULL,
  `PropertyandEquipmentGross` decimal(30,15) DEFAULT NULL,
  `TotalLongtermAssets` decimal(30,15) DEFAULT NULL,
  `TotalLongtermLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalSharesOutstanding` decimal(30,15) DEFAULT NULL,
  `ShorttermInvestments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balancefull_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_balancefull_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `TotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFQ` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFY` decimal(30,15) DEFAULT NULL,
  `CurrentPortionofLongtermDebt` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxLiabilitiesShortterm` decimal(30,15) DEFAULT NULL,
  `DeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `AccountsNotesReceivableNet` decimal(30,15) DEFAULT NULL,
  `AccountsPayable` decimal(30,15) DEFAULT NULL,
  `AccountsReceivableTradeNet` decimal(30,15) DEFAULT NULL,
  `AccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccumulatedDepreciation` decimal(30,15) DEFAULT NULL,
  `AmountsDuetoRelatedPartiesShortterm` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `IncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `LiabilitiesStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebt` decimal(30,15) DEFAULT NULL,
  `NotesPayable` decimal(30,15) DEFAULT NULL,
  `OperatingLeases` decimal(30,15) DEFAULT NULL,
  `OtherAccountsNotesReceivable` decimal(30,15) DEFAULT NULL,
  `OtherAccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `OtherBorrowings` decimal(30,15) DEFAULT NULL,
  `OtherReceivables` decimal(30,15) DEFAULT NULL,
  `PropertyandEquipmentGross` decimal(30,15) DEFAULT NULL,
  `TotalLongtermAssets` decimal(30,15) DEFAULT NULL,
  `TotalLongtermLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalSharesOutstanding` decimal(30,15) DEFAULT NULL,
  `ShorttermInvestments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_balancefull_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_balancefull_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `TotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFQ` decimal(30,15) DEFAULT NULL,
  `TotalAssetsFY` decimal(30,15) DEFAULT NULL,
  `CurrentPortionofLongtermDebt` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxLiabilitiesShortterm` decimal(30,15) DEFAULT NULL,
  `DeferredLiabilityCharges` decimal(30,15) DEFAULT NULL,
  `AccountsNotesReceivableNet` decimal(30,15) DEFAULT NULL,
  `AccountsPayable` decimal(30,15) DEFAULT NULL,
  `AccountsReceivableTradeNet` decimal(30,15) DEFAULT NULL,
  `AccruedExpenses` decimal(30,15) DEFAULT NULL,
  `AccumulatedDepreciation` decimal(30,15) DEFAULT NULL,
  `AmountsDuetoRelatedPartiesShortterm` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `IncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `LiabilitiesStockholdersEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebt` decimal(30,15) DEFAULT NULL,
  `NotesPayable` decimal(30,15) DEFAULT NULL,
  `OperatingLeases` decimal(30,15) DEFAULT NULL,
  `OtherAccountsNotesReceivable` decimal(30,15) DEFAULT NULL,
  `OtherAccountsPayableandAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `OtherBorrowings` decimal(30,15) DEFAULT NULL,
  `OtherReceivables` decimal(30,15) DEFAULT NULL,
  `PropertyandEquipmentGross` decimal(30,15) DEFAULT NULL,
  `TotalLongtermAssets` decimal(30,15) DEFAULT NULL,
  `TotalLongtermLiabilities` decimal(30,15) DEFAULT NULL,
  `TotalSharesOutstanding` decimal(30,15) DEFAULT NULL,
  `ShorttermInvestments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowconsolidated_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowconsolidated_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinDeferredRevenue` decimal(30,15) DEFAULT NULL,
  `ChangeinEquityNet` decimal(30,15) DEFAULT NULL,
  `ChangeinIncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `ChangeinInventories` decimal(30,15) DEFAULT NULL,
  `ChangeinOperatingAssetsLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinPrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `DividendsPaid` decimal(30,15) DEFAULT NULL,
  `EffectofExchangeRateonCash` decimal(30,15) DEFAULT NULL,
  `EmployeeCompensation` decimal(30,15) DEFAULT NULL,
  `AcquisitionSaleofBusinessNet` decimal(30,15) DEFAULT NULL,
  `AdjustmentforEquityEarnings` decimal(30,15) DEFAULT NULL,
  `AdjustmentforMinorityInterest` decimal(30,15) DEFAULT NULL,
  `AdjustmentforSpecialCharges` decimal(30,15) DEFAULT NULL,
  `CapitalExpenditures` decimal(30,15) DEFAULT NULL,
  `CashfromDiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `CashfromFinancingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromInvestingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromOperatingActivities` decimal(30,15) DEFAULT NULL,
  `CFDepreciationAmortization` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsPayableAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsReceivable` decimal(30,15) DEFAULT NULL,
  `InvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `NetChangeinCash` decimal(30,15) DEFAULT NULL,
  `OtherAdjustments` decimal(30,15) DEFAULT NULL,
  `OtherAssetLiabilityChangesNet` decimal(30,15) DEFAULT NULL,
  `OtherFinancingActivitiesNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestingActivities` decimal(30,15) DEFAULT NULL,
  `RealizedGainsLosses` decimal(30,15) DEFAULT NULL,
  `SaleofPropertyPlantEquipment` decimal(30,15) DEFAULT NULL,
  `StockOptionTaxBenefits` decimal(30,15) DEFAULT NULL,
  `TotalAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowconsolidated_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowconsolidated_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinDeferredRevenue` decimal(30,15) DEFAULT NULL,
  `ChangeinEquityNet` decimal(30,15) DEFAULT NULL,
  `ChangeinIncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `ChangeinInventories` decimal(30,15) DEFAULT NULL,
  `ChangeinOperatingAssetsLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinPrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `DividendsPaid` decimal(30,15) DEFAULT NULL,
  `EffectofExchangeRateonCash` decimal(30,15) DEFAULT NULL,
  `EmployeeCompensation` decimal(30,15) DEFAULT NULL,
  `AcquisitionSaleofBusinessNet` decimal(30,15) DEFAULT NULL,
  `AdjustmentforEquityEarnings` decimal(30,15) DEFAULT NULL,
  `AdjustmentforMinorityInterest` decimal(30,15) DEFAULT NULL,
  `AdjustmentforSpecialCharges` decimal(30,15) DEFAULT NULL,
  `CapitalExpenditures` decimal(30,15) DEFAULT NULL,
  `CashfromDiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `CashfromFinancingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromInvestingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromOperatingActivities` decimal(30,15) DEFAULT NULL,
  `CFDepreciationAmortization` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsPayableAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsReceivable` decimal(30,15) DEFAULT NULL,
  `InvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `NetChangeinCash` decimal(30,15) DEFAULT NULL,
  `OtherAdjustments` decimal(30,15) DEFAULT NULL,
  `OtherAssetLiabilityChangesNet` decimal(30,15) DEFAULT NULL,
  `OtherFinancingActivitiesNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestingActivities` decimal(30,15) DEFAULT NULL,
  `RealizedGainsLosses` decimal(30,15) DEFAULT NULL,
  `SaleofPropertyPlantEquipment` decimal(30,15) DEFAULT NULL,
  `StockOptionTaxBenefits` decimal(30,15) DEFAULT NULL,
  `TotalAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowconsolidated_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowconsolidated_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinDeferredRevenue` decimal(30,15) DEFAULT NULL,
  `ChangeinEquityNet` decimal(30,15) DEFAULT NULL,
  `ChangeinIncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `ChangeinInventories` decimal(30,15) DEFAULT NULL,
  `ChangeinOperatingAssetsLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinPrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `DividendsPaid` decimal(30,15) DEFAULT NULL,
  `EffectofExchangeRateonCash` decimal(30,15) DEFAULT NULL,
  `EmployeeCompensation` decimal(30,15) DEFAULT NULL,
  `AcquisitionSaleofBusinessNet` decimal(30,15) DEFAULT NULL,
  `AdjustmentforEquityEarnings` decimal(30,15) DEFAULT NULL,
  `AdjustmentforMinorityInterest` decimal(30,15) DEFAULT NULL,
  `AdjustmentforSpecialCharges` decimal(30,15) DEFAULT NULL,
  `CapitalExpenditures` decimal(30,15) DEFAULT NULL,
  `CashfromDiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `CashfromFinancingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromInvestingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromOperatingActivities` decimal(30,15) DEFAULT NULL,
  `CFDepreciationAmortization` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsPayableAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsReceivable` decimal(30,15) DEFAULT NULL,
  `InvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `NetChangeinCash` decimal(30,15) DEFAULT NULL,
  `OtherAdjustments` decimal(30,15) DEFAULT NULL,
  `OtherAssetLiabilityChangesNet` decimal(30,15) DEFAULT NULL,
  `OtherFinancingActivitiesNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestingActivities` decimal(30,15) DEFAULT NULL,
  `RealizedGainsLosses` decimal(30,15) DEFAULT NULL,
  `SaleofPropertyPlantEquipment` decimal(30,15) DEFAULT NULL,
  `StockOptionTaxBenefits` decimal(30,15) DEFAULT NULL,
  `TotalAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowconsolidated_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowconsolidated_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinDeferredRevenue` decimal(30,15) DEFAULT NULL,
  `ChangeinEquityNet` decimal(30,15) DEFAULT NULL,
  `ChangeinIncomeTaxesPayable` decimal(30,15) DEFAULT NULL,
  `ChangeinInventories` decimal(30,15) DEFAULT NULL,
  `ChangeinOperatingAssetsLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentAssets` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherCurrentLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinOtherLiabilities` decimal(30,15) DEFAULT NULL,
  `ChangeinPrepaidExpenses` decimal(30,15) DEFAULT NULL,
  `DividendsPaid` decimal(30,15) DEFAULT NULL,
  `EffectofExchangeRateonCash` decimal(30,15) DEFAULT NULL,
  `EmployeeCompensation` decimal(30,15) DEFAULT NULL,
  `AcquisitionSaleofBusinessNet` decimal(30,15) DEFAULT NULL,
  `AdjustmentforEquityEarnings` decimal(30,15) DEFAULT NULL,
  `AdjustmentforMinorityInterest` decimal(30,15) DEFAULT NULL,
  `AdjustmentforSpecialCharges` decimal(30,15) DEFAULT NULL,
  `CapitalExpenditures` decimal(30,15) DEFAULT NULL,
  `CashfromDiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `CashfromFinancingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromInvestingActivities` decimal(30,15) DEFAULT NULL,
  `CashfromOperatingActivities` decimal(30,15) DEFAULT NULL,
  `CFDepreciationAmortization` decimal(30,15) DEFAULT NULL,
  `DeferredIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsPayableAccruedExpenses` decimal(30,15) DEFAULT NULL,
  `ChangeinAccountsReceivable` decimal(30,15) DEFAULT NULL,
  `InvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `NetChangeinCash` decimal(30,15) DEFAULT NULL,
  `OtherAdjustments` decimal(30,15) DEFAULT NULL,
  `OtherAssetLiabilityChangesNet` decimal(30,15) DEFAULT NULL,
  `OtherFinancingActivitiesNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestingActivities` decimal(30,15) DEFAULT NULL,
  `RealizedGainsLosses` decimal(30,15) DEFAULT NULL,
  `SaleofPropertyPlantEquipment` decimal(30,15) DEFAULT NULL,
  `StockOptionTaxBenefits` decimal(30,15) DEFAULT NULL,
  `TotalAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowfull_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowfull_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinLongtermDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinShorttermBorrowingsNet` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsBeginningofYear` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsEndofYear` decimal(30,15) DEFAULT NULL,
  `CashPaidforIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `CashPaidforInterestExpense` decimal(30,15) DEFAULT NULL,
  `CFNetIncome` decimal(30,15) DEFAULT NULL,
  `IssuanceofEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebtPayments` decimal(30,15) DEFAULT NULL,
  `LongtermDebtProceeds` decimal(30,15) DEFAULT NULL,
  `OtherDebtNet` decimal(30,15) DEFAULT NULL,
  `OtherEquityTransactionsNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `PurchaseofInvestments` decimal(30,15) DEFAULT NULL,
  `RepurchaseofEquity` decimal(30,15) DEFAULT NULL,
  `SaleofInvestments` decimal(30,15) DEFAULT NULL,
  `ShorttermBorrowings` decimal(30,15) DEFAULT NULL,
  `TotalNoncashAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowfull_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowfull_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinLongtermDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinShorttermBorrowingsNet` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsBeginningofYear` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsEndofYear` decimal(30,15) DEFAULT NULL,
  `CashPaidforIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `CashPaidforInterestExpense` decimal(30,15) DEFAULT NULL,
  `CFNetIncome` decimal(30,15) DEFAULT NULL,
  `IssuanceofEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebtPayments` decimal(30,15) DEFAULT NULL,
  `LongtermDebtProceeds` decimal(30,15) DEFAULT NULL,
  `OtherDebtNet` decimal(30,15) DEFAULT NULL,
  `OtherEquityTransactionsNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `PurchaseofInvestments` decimal(30,15) DEFAULT NULL,
  `RepurchaseofEquity` decimal(30,15) DEFAULT NULL,
  `SaleofInvestments` decimal(30,15) DEFAULT NULL,
  `ShorttermBorrowings` decimal(30,15) DEFAULT NULL,
  `TotalNoncashAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowfull_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowfull_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinLongtermDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinShorttermBorrowingsNet` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsBeginningofYear` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsEndofYear` decimal(30,15) DEFAULT NULL,
  `CashPaidforIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `CashPaidforInterestExpense` decimal(30,15) DEFAULT NULL,
  `CFNetIncome` decimal(30,15) DEFAULT NULL,
  `IssuanceofEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebtPayments` decimal(30,15) DEFAULT NULL,
  `LongtermDebtProceeds` decimal(30,15) DEFAULT NULL,
  `OtherDebtNet` decimal(30,15) DEFAULT NULL,
  `OtherEquityTransactionsNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `PurchaseofInvestments` decimal(30,15) DEFAULT NULL,
  `RepurchaseofEquity` decimal(30,15) DEFAULT NULL,
  `SaleofInvestments` decimal(30,15) DEFAULT NULL,
  `ShorttermBorrowings` decimal(30,15) DEFAULT NULL,
  `TotalNoncashAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_cashflowfull_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_cashflowfull_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `ChangeinLongtermDebtNet` decimal(30,15) DEFAULT NULL,
  `ChangeinShorttermBorrowingsNet` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsBeginningofYear` decimal(30,15) DEFAULT NULL,
  `CashandCashEquivalentsEndofYear` decimal(30,15) DEFAULT NULL,
  `CashPaidforIncomeTaxes` decimal(30,15) DEFAULT NULL,
  `CashPaidforInterestExpense` decimal(30,15) DEFAULT NULL,
  `CFNetIncome` decimal(30,15) DEFAULT NULL,
  `IssuanceofEquity` decimal(30,15) DEFAULT NULL,
  `LongtermDebtPayments` decimal(30,15) DEFAULT NULL,
  `LongtermDebtProceeds` decimal(30,15) DEFAULT NULL,
  `OtherDebtNet` decimal(30,15) DEFAULT NULL,
  `OtherEquityTransactionsNet` decimal(30,15) DEFAULT NULL,
  `OtherInvestmentChangesNet` decimal(30,15) DEFAULT NULL,
  `PurchaseofInvestments` decimal(30,15) DEFAULT NULL,
  `RepurchaseofEquity` decimal(30,15) DEFAULT NULL,
  `SaleofInvestments` decimal(30,15) DEFAULT NULL,
  `ShorttermBorrowings` decimal(30,15) DEFAULT NULL,
  `TotalNoncashAdjustments` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_gf_data_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_gf_data_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `InterestIncome` decimal(18,3) DEFAULT NULL,
  `InterestExpense` decimal(18,3) DEFAULT NULL,
  `EPSBasic` decimal(18,3) DEFAULT NULL,
  `EPSDiluted` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingDiluted` decimal(18,3) DEFAULT NULL,
  `InventoriesRawMaterialsComponents` decimal(18,3) DEFAULT NULL,
  `InventoriesWorkInProcess` decimal(18,3) DEFAULT NULL,
  `InventoriesInventoriesAdjustments` decimal(18,3) DEFAULT NULL,
  `InventoriesFinishedGoods` decimal(18,3) DEFAULT NULL,
  `InventoriesOther` decimal(18,3) DEFAULT NULL,
  `TotalInventories` decimal(18,3) DEFAULT NULL,
  `LandAndImprovements` decimal(18,3) DEFAULT NULL,
  `BuildingsAndImprovements` decimal(18,3) DEFAULT NULL,
  `MachineryFurnitureEquipment` decimal(18,3) DEFAULT NULL,
  `ConstructionInProgress` decimal(18,3) DEFAULT NULL,
  `GrossPropertyPlantandEquipment` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingBasic` decimal(18,3) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_gf_data_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_gf_data_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `InterestIncome` decimal(18,3) DEFAULT NULL,
  `InterestExpense` decimal(18,3) DEFAULT NULL,
  `EPSBasic` decimal(18,3) DEFAULT NULL,
  `EPSDiluted` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingDiluted` decimal(18,3) DEFAULT NULL,
  `InventoriesRawMaterialsComponents` decimal(18,3) DEFAULT NULL,
  `InventoriesWorkInProcess` decimal(18,3) DEFAULT NULL,
  `InventoriesInventoriesAdjustments` decimal(18,3) DEFAULT NULL,
  `InventoriesFinishedGoods` decimal(18,3) DEFAULT NULL,
  `InventoriesOther` decimal(18,3) DEFAULT NULL,
  `TotalInventories` decimal(18,3) DEFAULT NULL,
  `LandAndImprovements` decimal(18,3) DEFAULT NULL,
  `BuildingsAndImprovements` decimal(18,3) DEFAULT NULL,
  `MachineryFurnitureEquipment` decimal(18,3) DEFAULT NULL,
  `ConstructionInProgress` decimal(18,3) DEFAULT NULL,
  `GrossPropertyPlantandEquipment` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingBasic` decimal(18,3) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_gf_data_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_gf_data_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `InterestIncome` decimal(18,3) DEFAULT NULL,
  `InterestExpense` decimal(18,3) DEFAULT NULL,
  `EPSBasic` decimal(18,3) DEFAULT NULL,
  `EPSDiluted` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingDiluted` decimal(18,3) DEFAULT NULL,
  `InventoriesRawMaterialsComponents` decimal(18,3) DEFAULT NULL,
  `InventoriesWorkInProcess` decimal(18,3) DEFAULT NULL,
  `InventoriesInventoriesAdjustments` decimal(18,3) DEFAULT NULL,
  `InventoriesFinishedGoods` decimal(18,3) DEFAULT NULL,
  `InventoriesOther` decimal(18,3) DEFAULT NULL,
  `TotalInventories` decimal(18,3) DEFAULT NULL,
  `LandAndImprovements` decimal(18,3) DEFAULT NULL,
  `BuildingsAndImprovements` decimal(18,3) DEFAULT NULL,
  `MachineryFurnitureEquipment` decimal(18,3) DEFAULT NULL,
  `ConstructionInProgress` decimal(18,3) DEFAULT NULL,
  `GrossPropertyPlantandEquipment` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingBasic` decimal(18,3) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_gf_data_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_gf_data_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `InterestIncome` decimal(18,3) DEFAULT NULL,
  `InterestExpense` decimal(18,3) DEFAULT NULL,
  `EPSBasic` decimal(18,3) DEFAULT NULL,
  `EPSDiluted` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingDiluted` decimal(18,3) DEFAULT NULL,
  `InventoriesRawMaterialsComponents` decimal(18,3) DEFAULT NULL,
  `InventoriesWorkInProcess` decimal(18,3) DEFAULT NULL,
  `InventoriesInventoriesAdjustments` decimal(18,3) DEFAULT NULL,
  `InventoriesFinishedGoods` decimal(18,3) DEFAULT NULL,
  `InventoriesOther` decimal(18,3) DEFAULT NULL,
  `TotalInventories` decimal(18,3) DEFAULT NULL,
  `LandAndImprovements` decimal(18,3) DEFAULT NULL,
  `BuildingsAndImprovements` decimal(18,3) DEFAULT NULL,
  `MachineryFurnitureEquipment` decimal(18,3) DEFAULT NULL,
  `ConstructionInProgress` decimal(18,3) DEFAULT NULL,
  `GrossPropertyPlantandEquipment` decimal(18,3) DEFAULT NULL,
  `SharesOutstandingBasic` decimal(18,3) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomeconsolidated_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomeconsolidated_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `EBIT` decimal(30,15) DEFAULT NULL,
  `CostofRevenue` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `DiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `EquityEarnings` decimal(30,15) DEFAULT NULL,
  `AccountingChange` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `ExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `GrossProfit` decimal(30,15) DEFAULT NULL,
  `IncomebeforeExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `IncomeBeforeTaxes` decimal(30,15) DEFAULT NULL,
  `IncomeTaxes` decimal(30,15) DEFAULT NULL,
  `InterestExpense` decimal(30,15) DEFAULT NULL,
  `InterestIncome` decimal(30,15) DEFAULT NULL,
  `MinorityInterestEquityEarnings` decimal(30,15) DEFAULT NULL,
  `NetIncome` decimal(30,15) DEFAULT NULL,
  `NetIncomeApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `OperatingProfit` decimal(30,15) DEFAULT NULL,
  `OtherNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `OtherOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `ResearchDevelopmentExpense` decimal(30,15) DEFAULT NULL,
  `RestructuringRemediationImpairmentProvisions` decimal(30,15) DEFAULT NULL,
  `TotalRevenue` decimal(30,15) DEFAULT NULL,
  `SellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomeconsolidated_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomeconsolidated_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `EBIT` decimal(30,15) DEFAULT NULL,
  `CostofRevenue` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `DiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `EquityEarnings` decimal(30,15) DEFAULT NULL,
  `AccountingChange` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `ExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `GrossProfit` decimal(30,15) DEFAULT NULL,
  `IncomebeforeExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `IncomeBeforeTaxes` decimal(30,15) DEFAULT NULL,
  `IncomeTaxes` decimal(30,15) DEFAULT NULL,
  `InterestExpense` decimal(30,15) DEFAULT NULL,
  `InterestIncome` decimal(30,15) DEFAULT NULL,
  `MinorityInterestEquityEarnings` decimal(30,15) DEFAULT NULL,
  `NetIncome` decimal(30,15) DEFAULT NULL,
  `NetIncomeApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `OperatingProfit` decimal(30,15) DEFAULT NULL,
  `OtherNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `OtherOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `ResearchDevelopmentExpense` decimal(30,15) DEFAULT NULL,
  `RestructuringRemediationImpairmentProvisions` decimal(30,15) DEFAULT NULL,
  `TotalRevenue` decimal(30,15) DEFAULT NULL,
  `SellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomeconsolidated_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomeconsolidated_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `EBIT` decimal(30,15) DEFAULT NULL,
  `CostofRevenue` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `DiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `EquityEarnings` decimal(30,15) DEFAULT NULL,
  `AccountingChange` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `ExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `GrossProfit` decimal(30,15) DEFAULT NULL,
  `IncomebeforeExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `IncomeBeforeTaxes` decimal(30,15) DEFAULT NULL,
  `IncomeTaxes` decimal(30,15) DEFAULT NULL,
  `InterestExpense` decimal(30,15) DEFAULT NULL,
  `InterestIncome` decimal(30,15) DEFAULT NULL,
  `MinorityInterestEquityEarnings` decimal(30,15) DEFAULT NULL,
  `NetIncome` decimal(30,15) DEFAULT NULL,
  `NetIncomeApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `OperatingProfit` decimal(30,15) DEFAULT NULL,
  `OtherNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `OtherOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `ResearchDevelopmentExpense` decimal(30,15) DEFAULT NULL,
  `RestructuringRemediationImpairmentProvisions` decimal(30,15) DEFAULT NULL,
  `TotalRevenue` decimal(30,15) DEFAULT NULL,
  `SellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomeconsolidated_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomeconsolidated_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `EBIT` decimal(30,15) DEFAULT NULL,
  `CostofRevenue` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `DiscontinuedOperations` decimal(30,15) DEFAULT NULL,
  `EquityEarnings` decimal(30,15) DEFAULT NULL,
  `AccountingChange` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncome` decimal(30,15) DEFAULT NULL,
  `ExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `GrossProfit` decimal(30,15) DEFAULT NULL,
  `IncomebeforeExtraordinaryItems` decimal(30,15) DEFAULT NULL,
  `IncomeBeforeTaxes` decimal(30,15) DEFAULT NULL,
  `IncomeTaxes` decimal(30,15) DEFAULT NULL,
  `InterestExpense` decimal(30,15) DEFAULT NULL,
  `InterestIncome` decimal(30,15) DEFAULT NULL,
  `MinorityInterestEquityEarnings` decimal(30,15) DEFAULT NULL,
  `NetIncome` decimal(30,15) DEFAULT NULL,
  `NetIncomeApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `OperatingProfit` decimal(30,15) DEFAULT NULL,
  `OtherNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `OtherOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `ResearchDevelopmentExpense` decimal(30,15) DEFAULT NULL,
  `RestructuringRemediationImpairmentProvisions` decimal(30,15) DEFAULT NULL,
  `TotalRevenue` decimal(30,15) DEFAULT NULL,
  `SellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomefull_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomefull_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `AdjustedEBIT` decimal(30,15) DEFAULT NULL,
  `AdjustedEBITDA` decimal(30,15) DEFAULT NULL,
  `AdjustedNetIncome` decimal(30,15) DEFAULT NULL,
  `AftertaxMargin` decimal(30,15) DEFAULT NULL,
  `EBITDA` decimal(30,15) DEFAULT NULL,
  `GrossMargin` decimal(30,15) DEFAULT NULL,
  `NetOperatingProfitafterTax` decimal(30,15) DEFAULT NULL,
  `OperatingMargin` decimal(30,15) DEFAULT NULL,
  `RevenueFQ` decimal(30,15) DEFAULT NULL,
  `RevenueFY` decimal(30,15) DEFAULT NULL,
  `RevenueTTM` decimal(30,15) DEFAULT NULL,
  `CostOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `DepreciationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `DilutedWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `AmortizationExpense` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `BasicWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `GeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `LaborExpense` decimal(30,15) DEFAULT NULL,
  `NetIncomefromContinuingOperationsApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `InterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `NoncontrollingInterest` decimal(30,15) DEFAULT NULL,
  `NonoperatingGainsLosses` decimal(30,15) DEFAULT NULL,
  `OperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OtherGeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `OtherInterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `OtherRevenue` decimal(30,15) DEFAULT NULL,
  `OtherSellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  `PreferredDividends` decimal(30,15) DEFAULT NULL,
  `SalesMarketingExpense` decimal(30,15) DEFAULT NULL,
  `TotalNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `TotalOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OperatingRevenue` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomefull_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomefull_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `AdjustedEBIT` decimal(30,15) DEFAULT NULL,
  `AdjustedEBITDA` decimal(30,15) DEFAULT NULL,
  `AdjustedNetIncome` decimal(30,15) DEFAULT NULL,
  `AftertaxMargin` decimal(30,15) DEFAULT NULL,
  `EBITDA` decimal(30,15) DEFAULT NULL,
  `GrossMargin` decimal(30,15) DEFAULT NULL,
  `NetOperatingProfitafterTax` decimal(30,15) DEFAULT NULL,
  `OperatingMargin` decimal(30,15) DEFAULT NULL,
  `RevenueFQ` decimal(30,15) DEFAULT NULL,
  `RevenueFY` decimal(30,15) DEFAULT NULL,
  `RevenueTTM` decimal(30,15) DEFAULT NULL,
  `CostOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `DepreciationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `DilutedWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `AmortizationExpense` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `BasicWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `GeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `LaborExpense` decimal(30,15) DEFAULT NULL,
  `NetIncomefromContinuingOperationsApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `InterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `NoncontrollingInterest` decimal(30,15) DEFAULT NULL,
  `NonoperatingGainsLosses` decimal(30,15) DEFAULT NULL,
  `OperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OtherGeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `OtherInterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `OtherRevenue` decimal(30,15) DEFAULT NULL,
  `OtherSellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  `PreferredDividends` decimal(30,15) DEFAULT NULL,
  `SalesMarketingExpense` decimal(30,15) DEFAULT NULL,
  `TotalNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `TotalOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OperatingRevenue` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomefull_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomefull_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `AdjustedEBIT` decimal(30,15) DEFAULT NULL,
  `AdjustedEBITDA` decimal(30,15) DEFAULT NULL,
  `AdjustedNetIncome` decimal(30,15) DEFAULT NULL,
  `AftertaxMargin` decimal(30,15) DEFAULT NULL,
  `EBITDA` decimal(30,15) DEFAULT NULL,
  `GrossMargin` decimal(30,15) DEFAULT NULL,
  `NetOperatingProfitafterTax` decimal(30,15) DEFAULT NULL,
  `OperatingMargin` decimal(30,15) DEFAULT NULL,
  `RevenueFQ` decimal(30,15) DEFAULT NULL,
  `RevenueFY` decimal(30,15) DEFAULT NULL,
  `RevenueTTM` decimal(30,15) DEFAULT NULL,
  `CostOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `DepreciationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `DilutedWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `AmortizationExpense` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `BasicWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `GeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `LaborExpense` decimal(30,15) DEFAULT NULL,
  `NetIncomefromContinuingOperationsApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `InterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `NoncontrollingInterest` decimal(30,15) DEFAULT NULL,
  `NonoperatingGainsLosses` decimal(30,15) DEFAULT NULL,
  `OperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OtherGeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `OtherInterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `OtherRevenue` decimal(30,15) DEFAULT NULL,
  `OtherSellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  `PreferredDividends` decimal(30,15) DEFAULT NULL,
  `SalesMarketingExpense` decimal(30,15) DEFAULT NULL,
  `TotalNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `TotalOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OperatingRevenue` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_incomefull_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_incomefull_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `AdjustedEBIT` decimal(30,15) DEFAULT NULL,
  `AdjustedEBITDA` decimal(30,15) DEFAULT NULL,
  `AdjustedNetIncome` decimal(30,15) DEFAULT NULL,
  `AftertaxMargin` decimal(30,15) DEFAULT NULL,
  `EBITDA` decimal(30,15) DEFAULT NULL,
  `GrossMargin` decimal(30,15) DEFAULT NULL,
  `NetOperatingProfitafterTax` decimal(30,15) DEFAULT NULL,
  `OperatingMargin` decimal(30,15) DEFAULT NULL,
  `RevenueFQ` decimal(30,15) DEFAULT NULL,
  `RevenueFY` decimal(30,15) DEFAULT NULL,
  `RevenueTTM` decimal(30,15) DEFAULT NULL,
  `CostOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `DepreciationExpense` decimal(30,15) DEFAULT NULL,
  `DilutedEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `DilutedWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `AmortizationExpense` decimal(30,15) DEFAULT NULL,
  `BasicEPSNetIncomefromContinuingOperations` decimal(30,15) DEFAULT NULL,
  `BasicWeightedAverageShares` decimal(30,15) DEFAULT NULL,
  `GeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `LaborExpense` decimal(30,15) DEFAULT NULL,
  `NetIncomefromContinuingOperationsApplicabletoCommon` decimal(30,15) DEFAULT NULL,
  `InterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `NoncontrollingInterest` decimal(30,15) DEFAULT NULL,
  `NonoperatingGainsLosses` decimal(30,15) DEFAULT NULL,
  `OperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OtherGeneralAdministrativeExpense` decimal(30,15) DEFAULT NULL,
  `OtherInterestIncomeExpenseNet` decimal(30,15) DEFAULT NULL,
  `OtherRevenue` decimal(30,15) DEFAULT NULL,
  `OtherSellingGeneralAdministrativeExpenses` decimal(30,15) DEFAULT NULL,
  `PreferredDividends` decimal(30,15) DEFAULT NULL,
  `SalesMarketingExpense` decimal(30,15) DEFAULT NULL,
  `TotalNonoperatingIncomeExpense` decimal(30,15) DEFAULT NULL,
  `TotalOperatingExpenses` decimal(30,15) DEFAULT NULL,
  `OperatingRevenue` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_variable_ratios_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_variable_ratios_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `BookEquity` decimal(30,15) DEFAULT NULL,
  `DebttoAssets` decimal(30,15) DEFAULT NULL,
  `DegreeofCombinedLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofFinancialLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofOperationalLeverage` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `DebttoEquity` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSBasic` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSDiluted` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonEquity` decimal(30,15) DEFAULT NULL,
  `ReturnonInvestedCapital` decimal(30,15) DEFAULT NULL,
  `RevenueperEmployee` decimal(30,15) DEFAULT NULL,
  `CashRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowMargin` decimal(30,15) DEFAULT NULL,
  `LongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoLongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoTotalCapital` decimal(30,15) DEFAULT NULL,
  `NetDebt` decimal(30,15) DEFAULT NULL,
  `NetIncomeperEmployee` decimal(30,15) DEFAULT NULL,
  `NetWorkingCapital` decimal(30,15) DEFAULT NULL,
  `PretaxMargin` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `TaxRate` decimal(30,15) DEFAULT NULL,
  `TotalCapital` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_variable_ratios_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_variable_ratios_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `BookEquity` decimal(30,15) DEFAULT NULL,
  `DebttoAssets` decimal(30,15) DEFAULT NULL,
  `DegreeofCombinedLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofFinancialLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofOperationalLeverage` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `DebttoEquity` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSBasic` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSDiluted` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonEquity` decimal(30,15) DEFAULT NULL,
  `ReturnonInvestedCapital` decimal(30,15) DEFAULT NULL,
  `RevenueperEmployee` decimal(30,15) DEFAULT NULL,
  `CashRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowMargin` decimal(30,15) DEFAULT NULL,
  `LongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoLongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoTotalCapital` decimal(30,15) DEFAULT NULL,
  `NetDebt` decimal(30,15) DEFAULT NULL,
  `NetIncomeperEmployee` decimal(30,15) DEFAULT NULL,
  `NetWorkingCapital` decimal(30,15) DEFAULT NULL,
  `PretaxMargin` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `TaxRate` decimal(30,15) DEFAULT NULL,
  `TotalCapital` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_variable_ratios_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_variable_ratios_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `BookEquity` decimal(30,15) DEFAULT NULL,
  `DebttoAssets` decimal(30,15) DEFAULT NULL,
  `DegreeofCombinedLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofFinancialLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofOperationalLeverage` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `DebttoEquity` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSBasic` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSDiluted` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonEquity` decimal(30,15) DEFAULT NULL,
  `ReturnonInvestedCapital` decimal(30,15) DEFAULT NULL,
  `RevenueperEmployee` decimal(30,15) DEFAULT NULL,
  `CashRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowMargin` decimal(30,15) DEFAULT NULL,
  `LongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoLongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoTotalCapital` decimal(30,15) DEFAULT NULL,
  `NetDebt` decimal(30,15) DEFAULT NULL,
  `NetIncomeperEmployee` decimal(30,15) DEFAULT NULL,
  `NetWorkingCapital` decimal(30,15) DEFAULT NULL,
  `PretaxMargin` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `TaxRate` decimal(30,15) DEFAULT NULL,
  `TotalCapital` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_variable_ratios_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_variable_ratios_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `BookEquity` decimal(30,15) DEFAULT NULL,
  `DebttoAssets` decimal(30,15) DEFAULT NULL,
  `DegreeofCombinedLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofFinancialLeverage` decimal(30,15) DEFAULT NULL,
  `DegreeofOperationalLeverage` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `DebttoEquity` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSBasic` decimal(30,15) DEFAULT NULL,
  `AdjustedEPSDiluted` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonAssets` decimal(30,15) DEFAULT NULL,
  `ReturnonEquity` decimal(30,15) DEFAULT NULL,
  `ReturnonInvestedCapital` decimal(30,15) DEFAULT NULL,
  `RevenueperEmployee` decimal(30,15) DEFAULT NULL,
  `CashRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `FreeCashFlowMargin` decimal(30,15) DEFAULT NULL,
  `LongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoLongTermCapital` decimal(30,15) DEFAULT NULL,
  `LongTermDebttoTotalCapital` decimal(30,15) DEFAULT NULL,
  `NetDebt` decimal(30,15) DEFAULT NULL,
  `NetIncomeperEmployee` decimal(30,15) DEFAULT NULL,
  `NetWorkingCapital` decimal(30,15) DEFAULT NULL,
  `PretaxMargin` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `TaxRate` decimal(30,15) DEFAULT NULL,
  `TotalCapital` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_financialscustom_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_financialscustom_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `COGSPercent` decimal(30,15) DEFAULT NULL,
  `GrossMarginPercent` decimal(30,15) DEFAULT NULL,
  `SGAPercent` decimal(30,15) DEFAULT NULL,
  `RDPercent` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationPercent` decimal(30,15) DEFAULT NULL,
  `EBITDAPercent` decimal(30,15) DEFAULT NULL,
  `OperatingMarginPercent` decimal(30,15) DEFAULT NULL,
  `EBITPercent` decimal(30,15) DEFAULT NULL,
  `TaxRatePercent` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `NetMarginPercent` decimal(30,15) DEFAULT NULL,
  `DividendsPerShare` decimal(30,15) DEFAULT NULL,
  `ShortTermDebtAndCurrentPortion` decimal(30,15) DEFAULT NULL,
  `TotalLongTermDebtAndNotesPayable` decimal(30,15) DEFAULT NULL,
  `NetChangeLongTermDebt` decimal(30,15) DEFAULT NULL,
  `CapEx` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `OwnerEarningsFCF` decimal(30,15) DEFAULT NULL,
  `SalesPercChange` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_financialscustom_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_financialscustom_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `COGSPercent` decimal(30,15) DEFAULT NULL,
  `GrossMarginPercent` decimal(30,15) DEFAULT NULL,
  `SGAPercent` decimal(30,15) DEFAULT NULL,
  `RDPercent` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationPercent` decimal(30,15) DEFAULT NULL,
  `EBITDAPercent` decimal(30,15) DEFAULT NULL,
  `OperatingMarginPercent` decimal(30,15) DEFAULT NULL,
  `EBITPercent` decimal(30,15) DEFAULT NULL,
  `TaxRatePercent` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `NetMarginPercent` decimal(30,15) DEFAULT NULL,
  `DividendsPerShare` decimal(30,15) DEFAULT NULL,
  `ShortTermDebtAndCurrentPortion` decimal(30,15) DEFAULT NULL,
  `TotalLongTermDebtAndNotesPayable` decimal(30,15) DEFAULT NULL,
  `NetChangeLongTermDebt` decimal(30,15) DEFAULT NULL,
  `CapEx` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `OwnerEarningsFCF` decimal(30,15) DEFAULT NULL,
  `SalesPercChange` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_financialscustom_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_financialscustom_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `COGSPercent` decimal(30,15) DEFAULT NULL,
  `GrossMarginPercent` decimal(30,15) DEFAULT NULL,
  `SGAPercent` decimal(30,15) DEFAULT NULL,
  `RDPercent` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationPercent` decimal(30,15) DEFAULT NULL,
  `EBITDAPercent` decimal(30,15) DEFAULT NULL,
  `OperatingMarginPercent` decimal(30,15) DEFAULT NULL,
  `EBITPercent` decimal(30,15) DEFAULT NULL,
  `TaxRatePercent` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `NetMarginPercent` decimal(30,15) DEFAULT NULL,
  `DividendsPerShare` decimal(30,15) DEFAULT NULL,
  `ShortTermDebtAndCurrentPortion` decimal(30,15) DEFAULT NULL,
  `TotalLongTermDebtAndNotesPayable` decimal(30,15) DEFAULT NULL,
  `NetChangeLongTermDebt` decimal(30,15) DEFAULT NULL,
  `CapEx` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `OwnerEarningsFCF` decimal(30,15) DEFAULT NULL,
  `SalesPercChange` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_financialscustom_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_financialscustom_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `COGSPercent` decimal(30,15) DEFAULT NULL,
  `GrossMarginPercent` decimal(30,15) DEFAULT NULL,
  `SGAPercent` decimal(30,15) DEFAULT NULL,
  `RDPercent` decimal(30,15) DEFAULT NULL,
  `DepreciationAmortizationPercent` decimal(30,15) DEFAULT NULL,
  `EBITDAPercent` decimal(30,15) DEFAULT NULL,
  `OperatingMarginPercent` decimal(30,15) DEFAULT NULL,
  `EBITPercent` decimal(30,15) DEFAULT NULL,
  `TaxRatePercent` decimal(30,15) DEFAULT NULL,
  `IncomeAfterTaxes` decimal(30,15) DEFAULT NULL,
  `NetMarginPercent` decimal(30,15) DEFAULT NULL,
  `DividendsPerShare` decimal(30,15) DEFAULT NULL,
  `ShortTermDebtAndCurrentPortion` decimal(30,15) DEFAULT NULL,
  `TotalLongTermDebtAndNotesPayable` decimal(30,15) DEFAULT NULL,
  `NetChangeLongTermDebt` decimal(30,15) DEFAULT NULL,
  `CapEx` decimal(30,15) DEFAULT NULL,
  `FreeCashFlow` decimal(30,15) DEFAULT NULL,
  `OwnerEarningsFCF` decimal(30,15) DEFAULT NULL,
  `SalesPercChange` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_key_ratios_3cagr`;
CREATE TABLE IF NOT EXISTS `reports_key_ratios_3cagr` (
  `report_id` bigint(20) NOT NULL,
  `SharesOutstandingDiluted` decimal(30,15) DEFAULT NULL,
  `ReportDatePrice` decimal(30,15) DEFAULT NULL,
  `CashFlow` decimal(30,15) DEFAULT NULL,
  `MarketCap` decimal(30,15) DEFAULT NULL,
  `EnterpriseValue` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `TangibleBookValue` decimal(30,15) DEFAULT NULL,
  `ExcessCash` decimal(30,15) DEFAULT NULL,
  `TotalInvestedCapital` decimal(30,15) DEFAULT NULL,
  `WorkingCapital` decimal(30,15) DEFAULT NULL,
  `P_E` decimal(30,15) DEFAULT NULL,
  `P_E_CashAdjusted` decimal(30,15) DEFAULT NULL,
  `EV_EBITDA` decimal(30,15) DEFAULT NULL,
  `EV_EBIT` decimal(30,15) DEFAULT NULL,
  `P_S` decimal(30,15) DEFAULT NULL,
  `P_BV` decimal(30,15) DEFAULT NULL,
  `P_Tang_BV` decimal(30,15) DEFAULT NULL,
  `P_CF` decimal(30,15) DEFAULT NULL,
  `P_FCF` decimal(30,15) DEFAULT NULL,
  `P_OwnerEarnings` decimal(30,15) DEFAULT NULL,
  `FCF_S` decimal(30,15) DEFAULT NULL,
  `FCFYield` decimal(30,15) DEFAULT NULL,
  `MagicFormulaEarningsYield` decimal(30,15) DEFAULT NULL,
  `ROE` decimal(30,15) DEFAULT NULL,
  `ROA` decimal(30,15) DEFAULT NULL,
  `ROIC` decimal(30,15) DEFAULT NULL,
  `CROIC` decimal(30,15) DEFAULT NULL,
  `GPA` decimal(30,15) DEFAULT NULL,
  `BooktoMarket` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `TotalDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `LongTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `ShortTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `AssetTurnover` decimal(30,15) DEFAULT NULL,
  `CashPercofRevenue` decimal(30,15) DEFAULT NULL,
  `ReceivablesPercofRevenue` decimal(30,15) DEFAULT NULL,
  `SG_APercofRevenue` decimal(30,15) DEFAULT NULL,
  `R_DPercofRevenue` decimal(30,15) DEFAULT NULL,
  `DaysSalesOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysInventoryOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysPayableOutstanding` decimal(30,15) DEFAULT NULL,
  `CashConversionCycle` decimal(30,15) DEFAULT NULL,
  `ReceivablesTurnover` decimal(30,15) DEFAULT NULL,
  `InventoryTurnover` decimal(30,15) DEFAULT NULL,
  `AverageAgeofInventory` decimal(30,15) DEFAULT NULL,
  `IntangiblesPercofBookValue` decimal(30,15) DEFAULT NULL,
  `InventoryPercofRevenue` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalDebtPercofTotalAssets` decimal(30,15) DEFAULT NULL,
  `WorkingCapitalPercofPrice` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_key_ratios_5cagr`;
CREATE TABLE IF NOT EXISTS `reports_key_ratios_5cagr` (
  `report_id` bigint(20) NOT NULL,
  `SharesOutstandingDiluted` decimal(30,15) DEFAULT NULL,
  `ReportDatePrice` decimal(30,15) DEFAULT NULL,
  `CashFlow` decimal(30,15) DEFAULT NULL,
  `MarketCap` decimal(30,15) DEFAULT NULL,
  `EnterpriseValue` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `TangibleBookValue` decimal(30,15) DEFAULT NULL,
  `ExcessCash` decimal(30,15) DEFAULT NULL,
  `TotalInvestedCapital` decimal(30,15) DEFAULT NULL,
  `WorkingCapital` decimal(30,15) DEFAULT NULL,
  `P_E` decimal(30,15) DEFAULT NULL,
  `P_E_CashAdjusted` decimal(30,15) DEFAULT NULL,
  `EV_EBITDA` decimal(30,15) DEFAULT NULL,
  `EV_EBIT` decimal(30,15) DEFAULT NULL,
  `P_S` decimal(30,15) DEFAULT NULL,
  `P_BV` decimal(30,15) DEFAULT NULL,
  `P_Tang_BV` decimal(30,15) DEFAULT NULL,
  `P_CF` decimal(30,15) DEFAULT NULL,
  `P_FCF` decimal(30,15) DEFAULT NULL,
  `P_OwnerEarnings` decimal(30,15) DEFAULT NULL,
  `FCF_S` decimal(30,15) DEFAULT NULL,
  `FCFYield` decimal(30,15) DEFAULT NULL,
  `MagicFormulaEarningsYield` decimal(30,15) DEFAULT NULL,
  `ROE` decimal(30,15) DEFAULT NULL,
  `ROA` decimal(30,15) DEFAULT NULL,
  `ROIC` decimal(30,15) DEFAULT NULL,
  `CROIC` decimal(30,15) DEFAULT NULL,
  `GPA` decimal(30,15) DEFAULT NULL,
  `BooktoMarket` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `TotalDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `LongTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `ShortTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `AssetTurnover` decimal(30,15) DEFAULT NULL,
  `CashPercofRevenue` decimal(30,15) DEFAULT NULL,
  `ReceivablesPercofRevenue` decimal(30,15) DEFAULT NULL,
  `SG_APercofRevenue` decimal(30,15) DEFAULT NULL,
  `R_DPercofRevenue` decimal(30,15) DEFAULT NULL,
  `DaysSalesOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysInventoryOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysPayableOutstanding` decimal(30,15) DEFAULT NULL,
  `CashConversionCycle` decimal(30,15) DEFAULT NULL,
  `ReceivablesTurnover` decimal(30,15) DEFAULT NULL,
  `InventoryTurnover` decimal(30,15) DEFAULT NULL,
  `AverageAgeofInventory` decimal(30,15) DEFAULT NULL,
  `IntangiblesPercofBookValue` decimal(30,15) DEFAULT NULL,
  `InventoryPercofRevenue` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalDebtPercofTotalAssets` decimal(30,15) DEFAULT NULL,
  `WorkingCapitalPercofPrice` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_key_ratios_7cagr`;
CREATE TABLE IF NOT EXISTS `reports_key_ratios_7cagr` (
  `report_id` bigint(20) NOT NULL,
  `SharesOutstandingDiluted` decimal(30,15) DEFAULT NULL,
  `ReportDatePrice` decimal(30,15) DEFAULT NULL,
  `CashFlow` decimal(30,15) DEFAULT NULL,
  `MarketCap` decimal(30,15) DEFAULT NULL,
  `EnterpriseValue` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `TangibleBookValue` decimal(30,15) DEFAULT NULL,
  `ExcessCash` decimal(30,15) DEFAULT NULL,
  `TotalInvestedCapital` decimal(30,15) DEFAULT NULL,
  `WorkingCapital` decimal(30,15) DEFAULT NULL,
  `P_E` decimal(30,15) DEFAULT NULL,
  `P_E_CashAdjusted` decimal(30,15) DEFAULT NULL,
  `EV_EBITDA` decimal(30,15) DEFAULT NULL,
  `EV_EBIT` decimal(30,15) DEFAULT NULL,
  `P_S` decimal(30,15) DEFAULT NULL,
  `P_BV` decimal(30,15) DEFAULT NULL,
  `P_Tang_BV` decimal(30,15) DEFAULT NULL,
  `P_CF` decimal(30,15) DEFAULT NULL,
  `P_FCF` decimal(30,15) DEFAULT NULL,
  `P_OwnerEarnings` decimal(30,15) DEFAULT NULL,
  `FCF_S` decimal(30,15) DEFAULT NULL,
  `FCFYield` decimal(30,15) DEFAULT NULL,
  `MagicFormulaEarningsYield` decimal(30,15) DEFAULT NULL,
  `ROE` decimal(30,15) DEFAULT NULL,
  `ROA` decimal(30,15) DEFAULT NULL,
  `ROIC` decimal(30,15) DEFAULT NULL,
  `CROIC` decimal(30,15) DEFAULT NULL,
  `GPA` decimal(30,15) DEFAULT NULL,
  `BooktoMarket` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `TotalDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `LongTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `ShortTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `AssetTurnover` decimal(30,15) DEFAULT NULL,
  `CashPercofRevenue` decimal(30,15) DEFAULT NULL,
  `ReceivablesPercofRevenue` decimal(30,15) DEFAULT NULL,
  `SG_APercofRevenue` decimal(30,15) DEFAULT NULL,
  `R_DPercofRevenue` decimal(30,15) DEFAULT NULL,
  `DaysSalesOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysInventoryOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysPayableOutstanding` decimal(30,15) DEFAULT NULL,
  `CashConversionCycle` decimal(30,15) DEFAULT NULL,
  `ReceivablesTurnover` decimal(30,15) DEFAULT NULL,
  `InventoryTurnover` decimal(30,15) DEFAULT NULL,
  `AverageAgeofInventory` decimal(30,15) DEFAULT NULL,
  `IntangiblesPercofBookValue` decimal(30,15) DEFAULT NULL,
  `InventoryPercofRevenue` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalDebtPercofTotalAssets` decimal(30,15) DEFAULT NULL,
  `WorkingCapitalPercofPrice` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `reports_key_ratios_10cagr`;
CREATE TABLE IF NOT EXISTS `reports_key_ratios_10cagr` (
  `report_id` bigint(20) NOT NULL,
  `SharesOutstandingDiluted` decimal(30,15) DEFAULT NULL,
  `ReportDatePrice` decimal(30,15) DEFAULT NULL,
  `CashFlow` decimal(30,15) DEFAULT NULL,
  `MarketCap` decimal(30,15) DEFAULT NULL,
  `EnterpriseValue` decimal(30,15) DEFAULT NULL,
  `GoodwillIntangibleAssetsNet` decimal(30,15) DEFAULT NULL,
  `TangibleBookValue` decimal(30,15) DEFAULT NULL,
  `ExcessCash` decimal(30,15) DEFAULT NULL,
  `TotalInvestedCapital` decimal(30,15) DEFAULT NULL,
  `WorkingCapital` decimal(30,15) DEFAULT NULL,
  `P_E` decimal(30,15) DEFAULT NULL,
  `P_E_CashAdjusted` decimal(30,15) DEFAULT NULL,
  `EV_EBITDA` decimal(30,15) DEFAULT NULL,
  `EV_EBIT` decimal(30,15) DEFAULT NULL,
  `P_S` decimal(30,15) DEFAULT NULL,
  `P_BV` decimal(30,15) DEFAULT NULL,
  `P_Tang_BV` decimal(30,15) DEFAULT NULL,
  `P_CF` decimal(30,15) DEFAULT NULL,
  `P_FCF` decimal(30,15) DEFAULT NULL,
  `P_OwnerEarnings` decimal(30,15) DEFAULT NULL,
  `FCF_S` decimal(30,15) DEFAULT NULL,
  `FCFYield` decimal(30,15) DEFAULT NULL,
  `MagicFormulaEarningsYield` decimal(30,15) DEFAULT NULL,
  `ROE` decimal(30,15) DEFAULT NULL,
  `ROA` decimal(30,15) DEFAULT NULL,
  `ROIC` decimal(30,15) DEFAULT NULL,
  `CROIC` decimal(30,15) DEFAULT NULL,
  `GPA` decimal(30,15) DEFAULT NULL,
  `BooktoMarket` decimal(30,15) DEFAULT NULL,
  `QuickRatio` decimal(30,15) DEFAULT NULL,
  `CurrentRatio` decimal(30,15) DEFAULT NULL,
  `TotalDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `LongTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `ShortTermDebt_EquityRatio` decimal(30,15) DEFAULT NULL,
  `AssetTurnover` decimal(30,15) DEFAULT NULL,
  `CashPercofRevenue` decimal(30,15) DEFAULT NULL,
  `ReceivablesPercofRevenue` decimal(30,15) DEFAULT NULL,
  `SG_APercofRevenue` decimal(30,15) DEFAULT NULL,
  `R_DPercofRevenue` decimal(30,15) DEFAULT NULL,
  `DaysSalesOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysInventoryOutstanding` decimal(30,15) DEFAULT NULL,
  `DaysPayableOutstanding` decimal(30,15) DEFAULT NULL,
  `CashConversionCycle` decimal(30,15) DEFAULT NULL,
  `ReceivablesTurnover` decimal(30,15) DEFAULT NULL,
  `InventoryTurnover` decimal(30,15) DEFAULT NULL,
  `AverageAgeofInventory` decimal(30,15) DEFAULT NULL,
  `IntangiblesPercofBookValue` decimal(30,15) DEFAULT NULL,
  `InventoryPercofRevenue` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofInvestedCapital` decimal(30,15) DEFAULT NULL,
  `LT_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `ST_DebtasPercofTotalDebt` decimal(30,15) DEFAULT NULL,
  `TotalDebtPercofTotalAssets` decimal(30,15) DEFAULT NULL,
  `WorkingCapitalPercofPrice` decimal(30,15) DEFAULT NULL,
  PRIMARY KEY (`report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

