<?php
function update_raw_data_tickers($dates, $rawdata) {
	$report_tables = array("reports_balanceconsolidated","reports_balancefull","reports_cashflowconsolidated","reports_cashflowfull","reports_financialheader","reports_gf_data","reports_incomeconsolidated","reports_incomefull","reports_metadata_eol","reports_variable_ratios");
	$ticker_tables = array("tickers_activity_daily_ratios", "tickers_growth_ratios", "tickers_leverage_ratios", "tickers_metadata_eol", "tickers_mini_ratios", "tickers_profitability_ratios", "tickers_valuation_ratios");

        //Delete all reports before updating to be sure we do not miss any manual update
        //as this is a batch process, it will not impact on the UE
        foreach($report_tables as $table) {
                $query = "DELETE FROM $table WHERE report_id IN (SELECT id FROM reports_header WHERE ticker_id = ".$dates->ticker_id.")";
                mysql_query($query) or die (mysql_error());
        }
        $query = "DELETE FROM reports_header WHERE ticker_id = ".$dates->ticker_id;
        mysql_query($query) or die (mysql_error());
        foreach($ticker_tables as $table) {
                $query = "DELETE FROM $table WHERE ticker_id = ".$dates->ticker_id;
                mysql_query($query) or die (mysql_error());
        }

        //Update tickers_* tables (tables that hold only 1 data point per symbol)
        //tickers_activity_daily_ratios
        $query = "INSERT INTO `tickers_activity_daily_ratios` (`ticker_id`, `AccountsPayableTurnoverDaysFY`, `TradeCycleDaysFY`, `TradeCycleDaysTTM`, `AccountsPayableTurnoverDaysTTM`, `InventoryTurnoverDaysFY`, `InventoryTurnoverDaysTTM`, `NetOperatingProfitafterTaxFQ`, `NetOperatingProfitafterTaxFY`, `NetOperatingProfitafterTaxTTM`, `ReceivablesCollectionPeriodDaysFY`, `ReceivablesCollectionPeriodDaysTTM`, `TaxRatePctFQ`, `TaxRatePctFY`, `TaxRatePctTTM`, `Volume`, `AverageVolume`, `Beta1Year`, `Beta3Year`, `Beta5Year`, `Date52WeekHigh`, `Date52WeekLow`, `DatePreviousClose`, `DatePriceClose`, `PreviousVolume`, `Price52WeekHigh`, `Price52WeekLow`, `PriceClose`, `PricePctChange13Week`, `PricePctChange1Day`, `PricePctChange1Week`, `PricePctChange26Week`, `PricePctChange4Week`, `PricePctChange52Week`, `PricePctChangeYTD`, `PricePreviousClose`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".$rawdata["AccountsPayableTurnoverDaysFY"][26]."',";
        $query .= "'".$rawdata["TradeCycleDaysFY"][26]."',";
        $query .= "'".$rawdata["TradeCycleDaysTTM"][26]."',";
        $query .= "'".$rawdata["AccountsPayableTurnoverDaysTTM"][26]."',";
        $query .= "'".$rawdata["InventoryTurnoverDaysFY"][26]."',";
        $query .= "'".$rawdata["InventoryTurnoverDaysTTM"][26]."',";
        $query .= "'".$rawdata["NetOperatingProfitafterTaxFQ"][26]."',";
        $query .= "'".$rawdata["NetOperatingProfitafterTaxFY"][26]."',";
        $query .= "'".$rawdata["NetOperatingProfitafterTaxTTM"][26]."',";
        $query .= "'".$rawdata["ReceivablesCollectionPeriodDaysFY"][26]."',";
        $query .= "'".$rawdata["ReceivablesCollectionPeriodDaysTTM"][26]."',";
        $query .= "'".$rawdata["TaxRatePctFQ"][26]."',";
        $query .= "'".$rawdata["TaxRatePctFY"][26]."',";
        $query .= "'".$rawdata["TaxRatePctTTM"][26]."',";
        $query .= "'".$rawdata["Volume"][26]."',";
        $query .= "'".$rawdata["AverageVolume"][26]."',";
        $query .= "'".$rawdata["Beta1Year"][26]."',";
        $query .= "'".$rawdata["Beta3Year"][26]."',";
        $query .= "'".$rawdata["Beta5Year"][26]."',";
        $query .= "'".date("Y-m-d",strtotime($rawdata["Date52WeekHigh"][26]))."',";
        $query .= "'".date("Y-m-d",strtotime($rawdata["Date52WeekLow"][26]))."',";
        $query .= "'".date("Y-m-d",strtotime($rawdata["DatePreviousClose"][26]))."',";
        $query .= "'".date("Y-m-d",strtotime($rawdata["DatePriceClose"][26]))."',";
        $query .= "'".$rawdata["PreviousVolume"][26]."',";
        $query .= "'".$rawdata["Price52WeekHigh"][26]."',";
        $query .= "'".$rawdata["Price52WeekLow"][26]."',";
        $query .= "'".$rawdata["PriceClose"][26]."',";
        $query .= "'".$rawdata["PricePctChange13Week"][26]."',";
        $query .= "'".$rawdata["PricePctChange1Day"][26]."',";
        $query .= "'".$rawdata["PricePctChange1Week"][26]."',";
        $query .= "'".$rawdata["PricePctChange26Week"][26]."',";
        $query .= "'".$rawdata["PricePctChange4Week"][26]."',";
        $query .= "'".$rawdata["PricePctChange52Week"][26]."',";
        $query .= "'".$rawdata["PricePctChangeYTD"][26]."',";
        $query .= "'".$rawdata["PricePreviousClose"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());
        //tickers_growth_ratios
        $query = "INSERT INTO `tickers_growth_ratios` (`ticker_id`, `AdjustedEBITDAPctGrowth3YearCAGRFY`, `AdjustedEBITDAPctGrowth5YearCAGRFY`, `AdjustedEBITDAPctGrowthFY`, `AdjustedEBITDAPctGrowthTTM`, `EBITDAPctGrowth3YearCAGRFY`, `EBITDAPctGrowth5YearCAGRFY`, `EBITDAPctGrowthFY`, `EBITDAPctGrowthTTM`, `EBITPctGrowth3YearCAGRFY`, `EBITPctGrowth5YearCAGRFY`, `EBITPctGrowthFY`, `EBITPctGrowthTTM`, `FreeCashFlowPctGrowth3YearCAGRFY`, `FreeCashFlowPctGrowth5YearCAGRFY`, `FreeCashFlowPctGrowthFY`, `FreeCashFlowPctGrowthTTM`, `NetIncomePctGrowth3YearCAGRFY`, `NetIncomePctGrowth5YearCAGRFY`, `NetIncomePctGrowthFY`, `NetIncomePctGrowthTTM`, `OperatingCashFlowPctGrowth3YearCAGRFY`, `OperatingCashFlowPctGrowth5YearCAGRFY`, `OperatingCashFlowPctGrowthFY`, `OperatingCashFlowPctGrowthTTM`, `OperatingProfitPctGrowth3YearCAGRFY`, `OperatingProfitPctGrowth5YearCAGRFY`, `OperatingProfitPctGrowthFY`, `OperatingProfitPctGrowthTTM`, `PriceEarningstoGrowthFY`, `PriceEarningstoGrowthTTM`, `RevenuePctGrowth3YearCAGRFY`, `RevenuePctGrowth5YearCAGRFY`, `RevenuePctGrowthFY`, `RevenuePctGrowthTTM`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".$rawdata["AdjustedEBITDAPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITDAPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITDAPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITDAPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["EBITDAPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["EBITDAPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["EBITDAPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["EBITDAPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["EBITPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["EBITPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["EBITPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["EBITPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["NetIncomePctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["NetIncomePctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["NetIncomePctGrowthFY"][26]."',";
        $query .= "'".$rawdata["NetIncomePctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["OperatingProfitPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["OperatingProfitPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["OperatingProfitPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["OperatingProfitPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["PriceEarningstoGrowthFY"][26]."',";
        $query .= "'".$rawdata["PriceEarningstoGrowthTTM"][26]."',";
        $query .= "'".$rawdata["RevenuePctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["RevenuePctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["RevenuePctGrowthFY"][26]."',";
        $query .= "'".$rawdata["RevenuePctGrowthTTM"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());
        //tickers_leverage_ratios
	$query = "INSERT INTO `tickers_leverage_ratios` (`ticker_id`, `TotalCapitalFY`, `TotalDebtFQ`, `TotalDebtFY`, `AltmanZscoreFY`, `AltmanZscoreTTM`, `BookEquityFQ`, `BookEquityFY`, `DebttoAssetsFQ`, `DebttoAssetsFY`, `DegreeofCombinedLeverageFY`, `DegreeofCombinedLeverageTTM`, `DegreeofFinancialLeverageFY`, `DegreeofFinancialLeverageTTM`, `DegreeofOperationalLeverageFY`, `DegreeofOperationalLeverageTTM`, `FreeCashFlowFQ`, `FreeCashFlowFY`, `FreeCashFlowtoEquityPctFY`, `FreeCashFlowtoEquityPctTTM`, `FreeCashFlowTTM`, `LongTermCapitalFQ`, `LongTermCapitalFY`, `LongTermDebttoLongTermCapitalFQ`, `LongTermDebttoLongTermCapitalFY`, `LongTermDebttoTotalCapitalFQ`, `LongTermDebttoTotalCapitalFY`, `NetDebtFQ`, `NetDebtFY`, `OperatingCashFlowFQ`, `OperatingCashFlowFY`, `OperatingCashFlowTTM`, `TotalCapitalFQ`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".$rawdata["TotalCapitalFY"][26]."',";
        $query .= "'".$rawdata["TotalDebtFQ"][26]."',";
        $query .= "'".$rawdata["TotalDebtFY"][26]."',";
        $query .= "'".$rawdata["AltmanZscoreFY"][26]."',";
        $query .= "'".$rawdata["AltmanZscoreTTM"][26]."',";
        $query .= "'".$rawdata["BookEquityFQ"][26]."',";
        $query .= "'".$rawdata["BookEquityFY"][26]."',";
        $query .= "'".$rawdata["DebttoAssetsFQ"][26]."',";
        $query .= "'".$rawdata["DebttoAssetsFY"][26]."',";
        $query .= "'".$rawdata["DegreeofCombinedLeverageFY"][26]."',";
        $query .= "'".$rawdata["DegreeofCombinedLeverageTTM"][26]."',";
        $query .= "'".$rawdata["DegreeofFinancialLeverageFY"][26]."',";
        $query .= "'".$rawdata["DegreeofFinancialLeverageTTM"][26]."',";
        $query .= "'".$rawdata["DegreeofOperationalLeverageFY"][26]."',";
        $query .= "'".$rawdata["DegreeofOperationalLeverageTTM"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowFQ"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowtoEquityPctFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowtoEquityPctTTM"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowTTM"][26]."',";
        $query .= "'".$rawdata["LongTermCapitalFQ"][26]."',";
        $query .= "'".$rawdata["LongTermCapitalFY"][26]."',";
        $query .= "'".$rawdata["LongTermDebttoLongTermCapitalFQ"][26]."',";
        $query .= "'".$rawdata["LongTermDebttoLongTermCapitalFY"][26]."',";
        $query .= "'".$rawdata["LongTermDebttoTotalCapitalFQ"][26]."',";
        $query .= "'".$rawdata["LongTermDebttoTotalCapitalFY"][26]."',";
        $query .= "'".$rawdata["NetDebtFQ"][26]."',";
        $query .= "'".$rawdata["NetDebtFY"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowFQ"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowFY"][26]."',";
        $query .= "'".$rawdata["OperatingCashFlowTTM"][26]."',";
        $query .= "'".$rawdata["TotalCapitalFQ"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());
	//tickers_mini_ratios
	$query = "INSERT INTO `tickers_mini_ratios` (`ticker_id`, `DebttoEquityFQ`, `DebttoEquityFY`, `MarketCapBasic`, `MarketCapDiluted`, `MarketCapTSO`, `PriceBookFQ`, `PriceBookFY`, `PriceEarningsFY`, `PriceEarningsTTM`, `GrossMarginPctFQ`, `GrossMarginPctFY`, `GrossMarginPctTTM`, `OperatingMarginPctFQ`, `OperatingMarginPctFY`, `OperatingMarginPctTTM`, `CashRatioFQ`, `CashRatioFY`, `NetWorkingCapitalFQ`, `NetWorkingCapitalFY`, `CurrentRatioFQ`, `CurrentRatioFY`, `QuickRatioFQ`, `QuickRatioFY`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".$rawdata["DebttoEquityFQ"][26]."',";
        $query .= "'".$rawdata["DebttoEquityFY"][26]."',";
        $query .= "'".$rawdata["MarketCapBasic"][26]."',";
        $query .= "'".$rawdata["MarketCapDiluted"][26]."',";
        $query .= "'".$rawdata["MarketCapTSO"][26]."',";
        $query .= "'".$rawdata["PriceBookFQ"][26]."',";
        $query .= "'".$rawdata["PriceBookFY"][26]."',";
        $query .= "'".$rawdata["PriceEarningsFY"][26]."',";
        $query .= "'".$rawdata["PriceEarningsTTM"][26]."',";
        $query .= "'".$rawdata["GrossMarginPctFQ"][26]."',";
        $query .= "'".$rawdata["GrossMarginPctFY"][26]."',";
        $query .= "'".$rawdata["GrossMarginPctTTM"][26]."',";
        $query .= "'".$rawdata["OperatingMarginPctFQ"][26]."',";
        $query .= "'".$rawdata["OperatingMarginPctFY"][26]."',";
        $query .= "'".$rawdata["OperatingMarginPctTTM"][26]."',";
        $query .= "'".$rawdata["CashRatioFQ"][26]."',";
        $query .= "'".$rawdata["CashRatioFY"][26]."',";
        $query .= "'".$rawdata["NetWorkingCapitalFQ"][26]."',";
        $query .= "'".$rawdata["NetWorkingCapitalFY"][26]."',";
        $query .= "'".$rawdata["CurrentRatioFQ"][26]."',";
        $query .= "'".$rawdata["CurrentRatioFY"][26]."',";
        $query .= "'".$rawdata["QuickRatioFQ"][26]."',";
        $query .= "'".$rawdata["QuickRatioFY"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());
	//tickers_profitability_ratios
	$query = "INSERT INTO `tickers_profitability_ratios` (`ticker_id`, `AdjustedEBITDAFQ`, `AdjustedEBITDAFY`, `AdjustedEBITDATTM`, `AdjustedEBITFQ`, `AdjustedEBITFY`, `AdjustedEBITPctGrowth3YearCAGRFY`, `AdjustedEBITPctGrowth5YearCAGRFY`, `AdjustedEBITPctGrowthFY`, `AdjustedEBITPctGrowthTTM`, `AdjustedEBITTTM`, `AdjustedNetIncomeFQ`, `AdjustedNetIncomeFY`, `AdjustedNetIncomePctGrowth3YearCAGRFY`, `AdjustedNetIncomePctGrowth5YearCAGRFY`, `AdjustedNetIncomePctGrowthFY`, `AdjustedNetIncomePctGrowthTTM`, `AdjustedNetIncomeTTM`, `AftertaxMarginPctFQ`, `AftertaxMarginPctFY`, `AftertaxMarginPctTTM`, `EBITDAFQ`, `EBITDAFY`, `EBITDATTM`, `EBITFQ`, `EBITFY`, `EBITTTM`, `FreeCashFlowMarginPctFQ`, `FreeCashFlowMarginPctFY`, `FreeCashFlowMarginPctTTM`, `FreeCashFlowReturnonAssetsPctFY`, `FreeCashFlowReturnonAssetsPctTTM`, `NetIncomeperEmployeeFY`, `NetIncomeperEmployeeTTM`, `PretaxMarginPctFQ`, `PretaxMarginPctFY`, `PretaxMarginPctTTM`, `ReturnonAssetsPctFY`, `ReturnonAssetsPctTTM`, `ReturnonEquityPctFY`, `ReturnonEquityPctTTM`, `ReturnonInvestedCapitalPctFY`, `ReturnonInvestedCapitalPctTTM`, `RevenueperEmployeeFY`, `RevenueperEmployeeTTM`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".$rawdata["AdjustedEBITDAFQ"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITDAFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITDATTM"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITFQ"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["AdjustedEBITTTM"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomeFQ"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomeFY"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomePctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomePctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomePctGrowthFY"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomePctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["AdjustedNetIncomeTTM"][26]."',";
        $query .= "'".$rawdata["AftertaxMarginPctFQ"][26]."',";
        $query .= "'".$rawdata["AftertaxMarginPctFY"][26]."',";
        $query .= "'".$rawdata["AftertaxMarginPctTTM"][26]."',";
        $query .= "'".$rawdata["EBITDAFQ"][26]."',";
        $query .= "'".$rawdata["EBITDAFY"][26]."',";
        $query .= "'".$rawdata["EBITDATTM"][26]."',";
        $query .= "'".$rawdata["EBITFQ"][26]."',";
        $query .= "'".$rawdata["EBITFY"][26]."',";
        $query .= "'".$rawdata["EBITTTM"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowMarginPctFQ"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowMarginPctFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowMarginPctTTM"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowReturnonAssetsPctFY"][26]."',";
        $query .= "'".$rawdata["FreeCashFlowReturnonAssetsPctTTM"][26]."',";
        $query .= "'".$rawdata["NetIncomeperEmployeeFY"][26]."',";
        $query .= "'".$rawdata["NetIncomeperEmployeeTTM"][26]."',";
        $query .= "'".$rawdata["PretaxMarginPctFQ"][26]."',";
        $query .= "'".$rawdata["PretaxMarginPctFY"][26]."',";
        $query .= "'".$rawdata["PretaxMarginPctTTM"][26]."',";
        $query .= "'".$rawdata["ReturnonAssetsPctFY"][26]."',";
        $query .= "'".$rawdata["ReturnonAssetsPctTTM"][26]."',";
        $query .= "'".$rawdata["ReturnonEquityPctFY"][26]."',";
        $query .= "'".$rawdata["ReturnonEquityPctTTM"][26]."',";
        $query .= "'".$rawdata["ReturnonInvestedCapitalPctFY"][26]."',";
        $query .= "'".$rawdata["ReturnonInvestedCapitalPctTTM"][26]."',";
        $query .= "'".$rawdata["RevenueperEmployeeFY"][26]."',";
        $query .= "'".$rawdata["RevenueperEmployeeTTM"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());
	//tickers_valuation_ratios
	$query = "INSERT INTO `tickers_valuation_ratios` (`ticker_id`, `TotalEquityFQ`, `TotalEquityFY`, `EarningsperShareNormalizedDilutedFQ`, `EarningsperShareNormalizedDilutedFY`, `EarningsperShareNormalizedDilutedTTM`, `AdjustedEPSDilutedPctGrowth3YearCAGRFY`, `AdjustedEPSDilutedPctGrowth5YearCAGRFY`, `AdjustedEPSDilutedPctGrowthFY`, `AdjustedEPSDilutedPctGrowthTTM`, `BasicAverageShares`, `DilutedAverageShares`, `DividendsperShareFQ`, `DividendsperShareFY`, `DividendsperShareTTM`, `EarningsperShareBasicFQ`, `EarningsperShareBasicFY`, `EarningsperShareBasicTTM`, `EarningsperShareDilutedFQ`, `EarningsperShareDilutedFY`, `EarningsperShareDilutedTTM`, `EnterpriseValueEBITDAFY`, `EnterpriseValueEBITDATTM`, `EnterpriseValueEBITFY`, `EnterpriseValueEBITTTM`, `EnterpriseValueFQ`, `EnterpriseValueFY`, `ExpectedAnnualDividends`, `PriceBookExclIntangiblesFQ`, `PriceBookExclIntangiblesFY`, `PriceEarningsNormalizedFY`, `PriceEarningsNormalizedTTM`, `PriceFreeCashFlowFY`, `PriceFreeCashFlowTTM`, `PriceRevenueFY`, `PriceRevenueTTM`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".$rawdata["TotalEquityFQ"][26]."',";
        $query .= "'".$rawdata["TotalEquityFY"][26]."',";
        $query .= "'".$rawdata["EarningsperShareNormalizedDilutedFQ"][26]."',";
        $query .= "'".$rawdata["EarningsperShareNormalizedDilutedFY"][26]."',";
        $query .= "'".$rawdata["EarningsperShareNormalizedDilutedTTM"][26]."',";
        $query .= "'".$rawdata["AdjustedEPSDilutedPctGrowth3YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEPSDilutedPctGrowth5YearCAGRFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEPSDilutedPctGrowthFY"][26]."',";
        $query .= "'".$rawdata["AdjustedEPSDilutedPctGrowthTTM"][26]."',";
        $query .= "'".$rawdata["BasicAverageShares"][26]."',";
        $query .= "'".$rawdata["DilutedAverageShares"][26]."',";
        $query .= "'".$rawdata["DividendsperShareFQ"][26]."',";
        $query .= "'".$rawdata["DividendsperShareFY"][26]."',";
        $query .= "'".$rawdata["DividendsperShareTTM"][26]."',";
        $query .= "'".$rawdata["EarningsperShareBasicFQ"][26]."',";
        $query .= "'".$rawdata["EarningsperShareBasicFY"][26]."',";
        $query .= "'".$rawdata["EarningsperShareBasicTTM"][26]."',";
        $query .= "'".$rawdata["EarningsperShareDilutedFQ"][26]."',";
        $query .= "'".$rawdata["EarningsperShareDilutedFY"][26]."',";
        $query .= "'".$rawdata["EarningsperShareDilutedTTM"][26]."',";
        $query .= "'".$rawdata["EnterpriseValueEBITDAFY"][26]."',";
        $query .= "'".$rawdata["EnterpriseValueEBITDATTM"][26]."',";
        $query .= "'".$rawdata["EnterpriseValueEBITFY"][26]."',";
        $query .= "'".$rawdata["EnterpriseValueEBITTTM"][26]."',";
        $query .= "'".$rawdata["EnterpriseValueFQ"][26]."',";
        $query .= "'".$rawdata["EnterpriseValueFY"][26]."',";
        $query .= "'".$rawdata["ExpectedAnnualDividends"][26]."',";
        $query .= "'".$rawdata["PriceBookExclIntangiblesFQ"][26]."',";
        $query .= "'".$rawdata["PriceBookExclIntangiblesFY"][26]."',";
        $query .= "'".$rawdata["PriceEarningsNormalizedFY"][26]."',";
        $query .= "'".$rawdata["PriceEarningsNormalizedTTM"][26]."',";
        $query .= "'".$rawdata["PriceFreeCashFlowFY"][26]."',";
        $query .= "'".$rawdata["PriceFreeCashFlowTTM"][26]."',";
        $query .= "'".$rawdata["PriceRevenueFY"][26]."',";
        $query .= "'".$rawdata["PriceRevenueTTM"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());
	//tickers_metadata_eol
	$query = "INSERT INTO `tickers_metadata_eol` (`ticker_id`, `TotalSharesOutstandingDate`, `BusinessDescription`, `CITY`, `Country`, `Formername`, `Industry`, `InvRelationsEmail`, `LastAnnualEPS`, `LastAnnualNetIncome`, `LastAnnualRevenue`, `LastAnnualTotalAssets`, `PhoneAreaCode`, `PhoneCountryCode`, `PhoneNumber`, `PublicFloat`, `PublicFloatDate`, `Sector`, `State`, `StateofIncorporation`, `StreetAddress1`, `StreetAddress2`, `TaxID`, `WebSiteURL`, `ZipCode`) VALUES (";
        $query .= "'".$dates->ticker_id."',";
        $query .= "'".date("Y-m-d",strtotime($rawdata["TotalSharesOutstandingDate"][26]))."',";
        $query .= "'".$rawdata["BusinessDescription"][26]."',";
        $query .= "'".$rawdata["CITY"][26]."',";
        $query .= "'".$rawdata["Country"][26]."',";
        $query .= "'".$rawdata["Formername"][26]."',";
        $query .= "'".$rawdata["Industry"][26]."',";
        $query .= "'".$rawdata["InvRelationsEmail"][26]."',";
        $query .= "'".$rawdata["LastAnnualEPS"][26]."',";
        $query .= "'".$rawdata["LastAnnualNetIncome"][26]."',";
        $query .= "'".$rawdata["LastAnnualRevenue"][26]."',";
        $query .= "'".$rawdata["LastAnnualTotalAssets"][26]."',";
        $query .= "'".$rawdata["PhoneAreaCode"][26]."',";
        $query .= "'".$rawdata["PhoneCountryCode"][26]."',";
        $query .= "'".$rawdata["PhoneNumber"][26]."',";
        $query .= "'".$rawdata["PublicFloat"][26]."',";
        $query .= "'".date("Y-m-d",strtotime($rawdata["PublicFloatDate"][26]))."',";
        $query .= "'".$rawdata["Sector"][26]."',";
        $query .= "'".$rawdata["State"][26]."',";
        $query .= "'".$rawdata["StateofIncorporation"][26]."',";
        $query .= "'".$rawdata["StreetAddress1"][26]."',";
        $query .= "'".$rawdata["StreetAddress2"][26]."',";
        $query .= "'".$rawdata["TaxID"][26]."',";
        $query .= "'".$rawdata["WebSiteURL"][26]."',";
        $query .= "'".$rawdata["ZipCode"][26]."'";
        $query .= ")";
        mysql_query($query) or die (mysql_error());

        //Update reports_* tables
	for($i=1; $i<27; $i++) {
	    if (!is_numeric($rawdata["duration"][$i])) {
        	//reports_header
		$query = "INSERT IGNORE INTO `reports_header` (`report_type`, `report_date`, `ticker_id`, `fiscal_year`, `fiscal_quarter`) VALUES (";
        	$query .= "'".$rawdata["duration"][$i]."',";
        	$query .= "'".date("Y-m-d",strtotime($rawdata["PeriodEndDate"][$i]))."',";
        	$query .= "'".$dates->ticker_id."',";
        	$query .= "'".$rawdata["fiscalYear"][$i]."',";
        	$query .= "'".$rawdata["FiscalQuarter"][$i]."'";
        	$query .= ")";
	        mysql_query($query) or die (mysql_error());
		if (mysql_affected_rows()>0) {
			$report_id = mysql_insert_id();
			//reports_balanceconsolidated
			$query = "INSERT INTO `reports_balanceconsolidated` (`report_id`, `CommitmentsContingencies`, `CommonStock`, `DeferredCharges`, `DeferredIncomeTaxesCurrent`, `DeferredIncomeTaxesLongterm`, `AccountsPayableandAccruedExpenses`, `AccruedInterest`, `AdditionalPaidinCapital`, `AdditionalPaidinCapitalPreferredStock`, `CashandCashEquivalents`, `CashCashEquivalentsandShorttermInvestments`, `Goodwill`, `IntangibleAssets`, `InventoriesNet`, `LongtermDeferredIncomeTaxLiabilities`, `LongtermDeferredLiabilityCharges`, `LongtermInvestments`, `MinorityInterest`, `OtherAccumulatedComprehensiveIncome`, `OtherAssets`, `OtherCurrentAssets`, `OtherCurrentLiabilities`, `OtherEquity`, `OtherInvestments`, `OtherLiabilities`, `PartnersCapital`, `PensionPostretirementObligation`, `PreferredStock`, `PrepaidExpenses`, `PropertyPlantEquipmentNet`, `RestrictedCash`, `RetainedEarnings`, `TemporaryEquity`, `TotalAssets`, `TotalCurrentAssets`, `TotalCurrentLiabilities`, `TotalLiabilities`, `TotalLongtermDebt`, `TotalReceivablesNet`, `TotalShorttermDebt`, `TotalStockholdersEquity`, `TreasuryStock`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["CommitmentsContingencies"][$i]."',";
        		$query .= "'".$rawdata["CommonStock"][$i]."',";
	        	$query .= "'".$rawdata["DeferredCharges"][$i]."',";
        		$query .= "'".$rawdata["DeferredIncomeTaxesCurrent"][$i]."',";
        		$query .= "'".$rawdata["DeferredIncomeTaxesLongterm"][$i]."',";
	        	$query .= "'".$rawdata["AccountsPayableandAccruedExpenses"][$i]."',";
        		$query .= "'".$rawdata["AccruedInterest"][$i]."',";
        		$query .= "'".$rawdata["AdditionalPaidinCapital"][$i]."',";
	        	$query .= "'".$rawdata["AdditionalPaidinCapitalPreferredStock"][$i]."',";
        		$query .= "'".$rawdata["CashandCashEquivalents"][$i]."',";
        		$query .= "'".$rawdata["CashCashEquivalentsandShorttermInvestments"][$i]."',";
	        	$query .= "'".$rawdata["Goodwill"][$i]."',";
        		$query .= "'".$rawdata["IntangibleAssets"][$i]."',";
        		$query .= "'".$rawdata["InventoriesNet"][$i]."',";
	        	$query .= "'".$rawdata["LongtermDeferredIncomeTaxLiabilities"][$i]."',";
        		$query .= "'".$rawdata["LongtermDeferredLiabilityCharges"][$i]."',";
        		$query .= "'".$rawdata["LongtermInvestments"][$i]."',";
	        	$query .= "'".$rawdata["MinorityInterest"][$i]."',";
        		$query .= "'".$rawdata["OtherAccumulatedComprehensiveIncome"][$i]."',";
        		$query .= "'".$rawdata["OtherAssets"][$i]."',";
	        	$query .= "'".$rawdata["OtherCurrentAssets"][$i]."',";
        		$query .= "'".$rawdata["OtherCurrentLiabilities"][$i]."',";
        		$query .= "'".$rawdata["OtherEquity"][$i]."',";
	        	$query .= "'".$rawdata["OtherInvestments"][$i]."',";
        		$query .= "'".$rawdata["OtherLiabilities"][$i]."',";
        		$query .= "'".$rawdata["PartnersCapital"][$i]."',";
	        	$query .= "'".$rawdata["PensionPostretirementObligation"][$i]."',";
        		$query .= "'".$rawdata["PreferredStock"][$i]."',";
        		$query .= "'".$rawdata["PrepaidExpenses"][$i]."',";
	        	$query .= "'".$rawdata["PropertyPlantEquipmentNet"][$i]."',";
        		$query .= "'".$rawdata["RestrictedCash"][$i]."',";
        		$query .= "'".$rawdata["RetainedEarnings"][$i]."',";
	        	$query .= "'".$rawdata["TemporaryEquity"][$i]."',";
        		$query .= "'".$rawdata["TotalAssets"][$i]."',";
        		$query .= "'".$rawdata["TotalCurrentAssets"][$i]."',";
	        	$query .= "'".$rawdata["TotalCurrentLiabilities"][$i]."',";
        		$query .= "'".$rawdata["TotalLiabilities"][$i]."',";
        		$query .= "'".$rawdata["TotalLongtermDebt"][$i]."',";
	        	$query .= "'".$rawdata["TotalReceivablesNet"][$i]."',";
        		$query .= "'".$rawdata["TotalShorttermDebt"][$i]."',";
        		$query .= "'".$rawdata["TotalStockholdersEquity"][$i]."',";
	        	$query .= "'".$rawdata["TreasuryStock"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_balancefull
			$query = "INSERT INTO `reports_balancefull` (`report_id`, `TotalDebt`, `TotalAssetsFQ`, `TotalAssetsFY`, `CurrentPortionofLongtermDebt`, `DeferredIncomeTaxLiabilitiesShortterm`, `DeferredLiabilityCharges`, `AccountsNotesReceivableNet`, `AccountsPayable`, `AccountsReceivableTradeNet`, `AccruedExpenses`, `AccumulatedDepreciation`, `AmountsDuetoRelatedPartiesShortterm`, `GoodwillIntangibleAssetsNet`, `IncomeTaxesPayable`, `LiabilitiesStockholdersEquity`, `LongtermDebt`, `NotesPayable`, `OperatingLeases`, `OtherAccountsNotesReceivable`, `OtherAccountsPayableandAccruedExpenses`, `OtherBorrowings`, `OtherReceivables`, `PropertyandEquipmentGross`, `TotalLongtermAssets`, `TotalLongtermLiabilities`, `TotalSharesOutstanding`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["TotalDebt"][$i]."',";
        		$query .= "'".$rawdata["TotalAssetsFQ"][$i]."',";
        		$query .= "'".$rawdata["TotalAssetsFY"][$i]."',";
        		$query .= "'".$rawdata["CurrentPortionofLongtermDebt"][$i]."',";
        		$query .= "'".$rawdata["DeferredIncomeTaxLiabilitiesShortterm"][$i]."',";
        		$query .= "'".$rawdata["DeferredLiabilityCharges"][$i]."',";
        		$query .= "'".$rawdata["AccountsNotesReceivableNet"][$i]."',";
        		$query .= "'".$rawdata["AccountsPayable"][$i]."',";
        		$query .= "'".$rawdata["AccountsReceivableTradeNet"][$i]."',";
        		$query .= "'".$rawdata["AccruedExpenses"][$i]."',";
        		$query .= "'".$rawdata["AccumulatedDepreciation"][$i]."',";
        		$query .= "'".$rawdata["AmountsDuetoRelatedPartiesShortterm"][$i]."',";
        		$query .= "'".$rawdata["GoodwillIntangibleAssetsNet"][$i]."',";
        		$query .= "'".$rawdata["IncomeTaxesPayable"][$i]."',";
        		$query .= "'".$rawdata["LiabilitiesStockholdersEquity"][$i]."',";
        		$query .= "'".$rawdata["LongtermDebt"][$i]."',";
        		$query .= "'".$rawdata["NotesPayable"][$i]."',";
        		$query .= "'".$rawdata["OperatingLeases"][$i]."',";
        		$query .= "'".$rawdata["OtherAccountsNotesReceivable"][$i]."',";
        		$query .= "'".$rawdata["OtherAccountsPayableandAccruedExpenses"][$i]."',";
        		$query .= "'".$rawdata["OtherBorrowings"][$i]."',";
        		$query .= "'".$rawdata["OtherReceivables"][$i]."',";
        		$query .= "'".$rawdata["PropertyandEquipmentGross"][$i]."',";
        		$query .= "'".$rawdata["TotalLongtermAssets"][$i]."',";
        		$query .= "'".$rawdata["TotalLongtermLiabilities"][$i]."',";
        		$query .= "'".$rawdata["TotalSharesOutstanding"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_cashflowconsolidated
			$query = "INSERT INTO `reports_cashflowconsolidated` (`report_id`, `ChangeinCurrentAssets`, `ChangeinCurrentLiabilities`, `ChangeinDebtNet`, `ChangeinDeferredRevenue`, `ChangeinEquityNet`, `ChangeinIncomeTaxesPayable`, `ChangeinInventories`, `ChangeinOperatingAssetsLiabilities`, `ChangeinOtherAssets`, `ChangeinOtherCurrentAssets`, `ChangeinOtherCurrentLiabilities`, `ChangeinOtherLiabilities`, `ChangeinPrepaidExpenses`, `DividendsPaid`, `EffectofExchangeRateonCash`, `EmployeeCompensation`, `AcquisitionSaleofBusinessNet`, `AdjustmentforEquityEarnings`, `AdjustmentforMinorityInterest`, `AdjustmentforSpecialCharges`, `CapitalExpenditures`, `CashfromDiscontinuedOperations`, `CashfromFinancingActivities`, `CashfromInvestingActivities`, `CashfromOperatingActivities`, `CFDepreciationAmortization`, `DeferredIncomeTaxes`, `ChangeinAccountsPayableAccruedExpenses`, `ChangeinAccountsReceivable`, `InvestmentChangesNet`, `NetChangeinCash`, `OtherAdjustments`, `OtherAssetLiabilityChangesNet`, `OtherFinancingActivitiesNet`, `OtherInvestingActivities`, `RealizedGainsLosses`, `SaleofPropertyPlantEquipment`, `StockOptionTaxBenefits`, `TotalAdjustments`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["ChangeinCurrentAssets"][$i]."',";
        		$query .= "'".$rawdata["ChangeinCurrentLiabilities"][$i]."',";
        		$query .= "'".$rawdata["ChangeinDebtNet"][$i]."',";
        		$query .= "'".$rawdata["ChangeinDeferredRevenue"][$i]."',";
        		$query .= "'".$rawdata["ChangeinEquityNet"][$i]."',";
        		$query .= "'".$rawdata["ChangeinIncomeTaxesPayable"][$i]."',";
        		$query .= "'".$rawdata["ChangeinInventories"][$i]."',";
        		$query .= "'".$rawdata["ChangeinOperatingAssetsLiabilities"][$i]."',";
        		$query .= "'".$rawdata["ChangeinOtherAssets"][$i]."',";
        		$query .= "'".$rawdata["ChangeinOtherCurrentAssets"][$i]."',";
        		$query .= "'".$rawdata["ChangeinOtherCurrentLiabilities"][$i]."',";
        		$query .= "'".$rawdata["ChangeinOtherLiabilities"][$i]."',";
        		$query .= "'".$rawdata["ChangeinPrepaidExpenses"][$i]."',";
        		$query .= "'".$rawdata["DividendsPaid"][$i]."',";
        		$query .= "'".$rawdata["EffectofExchangeRateonCash"][$i]."',";
        		$query .= "'".$rawdata["EmployeeCompensation"][$i]."',";
        		$query .= "'".$rawdata["AcquisitionSaleofBusinessNet"][$i]."',";
        		$query .= "'".$rawdata["AdjustmentforEquityEarnings"][$i]."',";
        		$query .= "'".$rawdata["AdjustmentforMinorityInterest"][$i]."',";
        		$query .= "'".$rawdata["AdjustmentforSpecialCharges"][$i]."',";
        		$query .= "'".$rawdata["CapitalExpenditures"][$i]."',";
        		$query .= "'".$rawdata["CashfromDiscontinuedOperations"][$i]."',";
        		$query .= "'".$rawdata["CashfromFinancingActivities"][$i]."',";
        		$query .= "'".$rawdata["CashfromInvestingActivities"][$i]."',";
        		$query .= "'".$rawdata["CashfromOperatingActivities"][$i]."',";
        		$query .= "'".$rawdata["CFDepreciationAmortization"][$i]."',";
        		$query .= "'".$rawdata["DeferredIncomeTaxes"][$i]."',";
        		$query .= "'".$rawdata["ChangeinAccountsPayableAccruedExpenses"][$i]."',";
        		$query .= "'".$rawdata["ChangeinAccountsReceivable"][$i]."',";
        		$query .= "'".$rawdata["InvestmentChangesNet"][$i]."',";
        		$query .= "'".$rawdata["NetChangeinCash"][$i]."',";
        		$query .= "'".$rawdata["OtherAdjustments"][$i]."',";
        		$query .= "'".$rawdata["OtherAssetLiabilityChangesNet"][$i]."',";
        		$query .= "'".$rawdata["OtherFinancingActivitiesNet"][$i]."',";
        		$query .= "'".$rawdata["OtherInvestingActivities"][$i]."',";
        		$query .= "'".$rawdata["RealizedGainsLosses"][$i]."',";
        		$query .= "'".$rawdata["SaleofPropertyPlantEquipment"][$i]."',";
        		$query .= "'".$rawdata["StockOptionTaxBenefits"][$i]."',";
        		$query .= "'".$rawdata["TotalAdjustments"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_cashflowfull
			$query = "INSERT INTO `reports_cashflowfull` (`report_id`, `ChangeinLongtermDebtNet`, `ChangeinShorttermBorrowingsNet`, `CashandCashEquivalentsBeginningofYear`, `CashandCashEquivalentsEndofYear`, `CashPaidforIncomeTaxes`, `CashPaidforInterestExpense`, `CFNetIncome`, `IssuanceofEquity`, `LongtermDebtPayments`, `LongtermDebtProceeds`, `OtherDebtNet`, `OtherEquityTransactionsNet`, `OtherInvestmentChangesNet`, `PurchaseofInvestments`, `RepurchaseofEquity`, `SaleofInvestments`, `ShorttermBorrowings`, `ShorttermInvestments`, `TotalNoncashAdjustments`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["ChangeinLongtermDebtNet"][$i]."',";
        		$query .= "'".$rawdata["ChangeinShorttermBorrowingsNet"][$i]."',";
        		$query .= "'".$rawdata["CashandCashEquivalentsBeginningofYear"][$i]."',";
        		$query .= "'".$rawdata["CashandCashEquivalentsEndofYear"][$i]."',";
        		$query .= "'".$rawdata["CashPaidforIncomeTaxes"][$i]."',";
        		$query .= "'".$rawdata["CashPaidforInterestExpense"][$i]."',";
        		$query .= "'".$rawdata["CFNetIncome"][$i]."',";
        		$query .= "'".$rawdata["IssuanceofEquity"][$i]."',";
        		$query .= "'".$rawdata["LongtermDebtPayments"][$i]."',";
        		$query .= "'".$rawdata["LongtermDebtProceeds"][$i]."',";
        		$query .= "'".$rawdata["OtherDebtNet"][$i]."',";
        		$query .= "'".$rawdata["OtherEquityTransactionsNet"][$i]."',";
        		$query .= "'".$rawdata["OtherInvestmentChangesNet"][$i]."',";
        		$query .= "'".$rawdata["PurchaseofInvestments"][$i]."',";
        		$query .= "'".$rawdata["RepurchaseofEquity"][$i]."',";
        		$query .= "'".$rawdata["SaleofInvestments"][$i]."',";
        		$query .= "'".$rawdata["ShorttermBorrowings"][$i]."',";
        		$query .= "'".$rawdata["ShorttermInvestments"][$i]."',";
        		$query .= "'".$rawdata["TotalNoncashAdjustments"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_financialheader
			$query = "INSERT INTO `reports_financialheader` (`report_id`, `USDConversionRate`, `Restated`, `ReceivedDate`, `Preliminary`, `PeriodLengthCode`, `PeriodLength`, `Original`, `FormType`, `FiledDate`, `DCN`, `CurrencyCode`, `CrossCalculated`, `Audited`, `Amended`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["USDConversionRate"][$i]."',";
        		$query .= "'".($rawdata["Restated"][$i] == "false" ? 0 : 1)."',";
        		$query .= "'".date("Y-m-d",strtotime($rawdata["ReceivedDate"][$i]))."',";
        		$query .= "'".($rawdata["Preliminary"][$i] == "false" ? 0 : 1)."',";
        		$query .= "'".$rawdata["PeriodLengthCode"][$i]."',";
        		$query .= "'".$rawdata["PeriodLength"][$i]."',";
        		$query .= "'".($rawdata["Original"][$i] == "false" ? 0 : 1)."',";
        		$query .= "'".$rawdata["FormType"][$i]."',";
        		$query .= "'".date("Y-m-d",strtotime($rawdata["FiledDate"][$i]))."',";
        		$query .= "'".$rawdata["DCN"][$i]."',";
        		$query .= "'".$rawdata["CurrencyCode"][$i]."',";
        		$query .= "'".($rawdata["CrossCalculated"][$i] == "false" ? 0 : 1)."',";
        		$query .= "'".($rawdata["Audited"][$i] == "false" ? 0 : 1)."',";
        		$query .= "'".($rawdata["Amended"][$i] == "false" ? 0 : 1)."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_gf_data
			$query = "INSERT INTO `reports_gf_data` (`report_id`, `fiscalPeriod_eol`, `fiscalPeriod_gf`, `InterestIncome`, `InterestExpense`, `EPSBasic`, `EPSDiluted`, `SharesOutstandingDiluted`, `InventoriesRawMaterialsComponents`, `InventoriesWorkInProcess`, `InventoriesInventoriesAdjustments`, `InventoriesFinishedGoods`, `InventoriesOther`, `TotalInventories`, `LandAndImprovements`, `BuildingsAndImprovements`, `MachineryFurnitureEquipment`, `ConstructionInProgress`, `GrossPropertyPlantandEquipment`, `SharesOutstandingBasic`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["fiscalPeriod"][$i]."',";
        		$query .= "'".$rawdata["FiscalPeriod"][$i]."',";
        		$query .= "'".$rawdata["InterestIncome"][$i]."',";
        		$query .= "'".$rawdata["InterestExpense"][$i]."',";
        		$query .= "'".$rawdata["EPSBasic"][$i]."',";
        		$query .= "'".$rawdata["EPSDiluted"][$i]."',";
        		$query .= "'".$rawdata["SharesOutstandingDiluted"][$i]."',";
        		$query .= "'".$rawdata["InventoriesRawMaterialsComponents"][$i]."',";
        		$query .= "'".$rawdata["InventoriesWorkInProcess"][$i]."',";
        		$query .= "'".$rawdata["InventoriesInventoriesAdjustments"][$i]."',";
        		$query .= "'".$rawdata["InventoriesFinishedGoods"][$i]."',";
        		$query .= "'".$rawdata["InventoriesOther"][$i]."',";
        		$query .= "'".$rawdata["TotalInventories"][$i]."',";
        		$query .= "'".$rawdata["LandAndImprovements"][$i]."',";
        		$query .= "'".$rawdata["BuildingsAndImprovements"][$i]."',";
        		$query .= "'".$rawdata["MachineryFurnitureEquipment"][$i]."',";
        		$query .= "'".$rawdata["ConstructionInProgress"][$i]."',";
        		$query .= "'".$rawdata["GrossPropertyPlantandEquipment"][$i]."',";
        		$query .= "'".$rawdata["SharesOutstandingBasic"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_incomeconsolidated
			$query = "INSERT INTO `reports_incomeconsolidated` (`report_id`, `EBIT`, `CostofRevenue`, `DepreciationAmortizationExpense`, `DilutedEPSNetIncome`, `DiscontinuedOperations`, `EquityEarnings`, `AccountingChange`, `BasicEPSNetIncome`, `ExtraordinaryItems`, `GrossProfit`, `IncomebeforeExtraordinaryItems`, `IncomeBeforeTaxes`, `IncomeTaxes`, `InterestExpense`, `InterestIncome`, `MinorityInterestEquityEarnings`, `NetIncome`, `NetIncomeApplicabletoCommon`, `OperatingProfit`, `OtherNonoperatingIncomeExpense`, `OtherOperatingExpenses`, `ResearchDevelopmentExpense`, `RestructuringRemediationImpairmentProvisions`, `TotalRevenue`, `SellingGeneralAdministrativeExpenses`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["EBIT"][$i]."',";
        		$query .= "'".$rawdata["CostofRevenue"][$i]."',";
        		$query .= "'".$rawdata["DepreciationAmortizationExpense"][$i]."',";
        		$query .= "'".$rawdata["DilutedEPSNetIncome"][$i]."',";
        		$query .= "'".$rawdata["DiscontinuedOperations"][$i]."',";
        		$query .= "'".$rawdata["EquityEarnings"][$i]."',";
        		$query .= "'".$rawdata["AccountingChange"][$i]."',";
        		$query .= "'".$rawdata["BasicEPSNetIncome"][$i]."',";
        		$query .= "'".$rawdata["ExtraordinaryItems"][$i]."',";
        		$query .= "'".$rawdata["GrossProfit"][$i]."',";
        		$query .= "'".$rawdata["IncomebeforeExtraordinaryItems"][$i]."',";
        		$query .= "'".$rawdata["IncomeBeforeTaxes"][$i]."',";
        		$query .= "'".$rawdata["IncomeTaxes"][$i]."',";
        		$query .= "'".$rawdata["InterestExpense"][$i]."',";
        		$query .= "'".$rawdata["InterestIncome"][$i]."',";
        		$query .= "'".$rawdata["MinorityInterestEquityEarnings"][$i]."',";
        		$query .= "'".$rawdata["NetIncome"][$i]."',";
        		$query .= "'".$rawdata["NetIncomeApplicabletoCommon"][$i]."',";
        		$query .= "'".$rawdata["OperatingProfit"][$i]."',";
        		$query .= "'".$rawdata["OtherNonoperatingIncomeExpense"][$i]."',";
        		$query .= "'".$rawdata["OtherOperatingExpenses"][$i]."',";
        		$query .= "'".$rawdata["ResearchDevelopmentExpense"][$i]."',";
        		$query .= "'".$rawdata["RestructuringRemediationImpairmentProvisions"][$i]."',";
        		$query .= "'".$rawdata["TotalRevenue"][$i]."',";
        		$query .= "'".$rawdata["SellingGeneralAdministrativeExpenses"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_incomefull
			$query = "INSERT INTO `reports_incomefull` (`report_id`, `AdjustedEBIT`, `AdjustedEBITDA`, `AdjustedNetIncome`, `AftertaxMargin`, `EBITDA`, `GrossMargin`, `NetOperatingProfitafterTax`, `OperatingMargin`, `RevenueFQ`, `RevenueFY`, `RevenueTTM`, `CostOperatingExpenses`, `DepreciationExpense`, `DilutedEPSNetIncomefromContinuingOperations`, `DilutedWeightedAverageShares`, `AmortizationExpense`, `BasicEPSNetIncomefromContinuingOperations`, `BasicWeightedAverageShares`, `GeneralAdministrativeExpense`, `IncomeAfterTaxes`, `LaborExpense`, `NetIncomefromContinuingOperationsApplicabletoCommon`, `InterestIncomeExpenseNet`, `NoncontrollingInterest`, `NonoperatingGainsLosses`, `OperatingExpenses`, `OtherGeneralAdministrativeExpense`, `OtherInterestIncomeExpenseNet`, `OtherRevenue`, `OtherSellingGeneralAdministrativeExpenses`, `PreferredDividends`, `SalesMarketingExpense`, `TotalNonoperatingIncomeExpense`, `TotalOperatingExpenses`, `OperatingRevenue`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["AdjustedEBIT"][$i]."',";
        		$query .= "'".$rawdata["AdjustedEBITDA"][$i]."',";
        		$query .= "'".$rawdata["AdjustedNetIncome"][$i]."',";
        		$query .= "'".$rawdata["AftertaxMargin"][$i]."',";
        		$query .= "'".$rawdata["EBITDA"][$i]."',";
        		$query .= "'".$rawdata["GrossMargin"][$i]."',";
        		$query .= "'".$rawdata["NetOperatingProfitafterTax"][$i]."',";
        		$query .= "'".$rawdata["OperatingMargin"][$i]."',";
        		$query .= "'".$rawdata["RevenueFQ"][$i]."',";
        		$query .= "'".$rawdata["RevenueFY"][$i]."',";
        		$query .= "'".$rawdata["RevenueTTM"][$i]."',";
        		$query .= "'".$rawdata["CostOperatingExpenses"][$i]."',";
        		$query .= "'".$rawdata["DepreciationExpense"][$i]."',";
        		$query .= "'".$rawdata["DilutedEPSNetIncomefromContinuingOperations"][$i]."',";
        		$query .= "'".$rawdata["DilutedWeightedAverageShares"][$i]."',";
        		$query .= "'".$rawdata["AmortizationExpense"][$i]."',";
        		$query .= "'".$rawdata["BasicEPSNetIncomefromContinuingOperations"][$i]."',";
        		$query .= "'".$rawdata["BasicWeightedAverageShares"][$i]."',";
        		$query .= "'".$rawdata["GeneralAdministrativeExpense"][$i]."',";
        		$query .= "'".$rawdata["IncomeAfterTaxes"][$i]."',";
        		$query .= "'".$rawdata["LaborExpense"][$i]."',";
        		$query .= "'".$rawdata["NetIncomefromContinuingOperationsApplicabletoCommon"][$i]."',";
        		$query .= "'".$rawdata["InterestIncomeExpenseNet"][$i]."',";
        		$query .= "'".$rawdata["NoncontrollingInterest"][$i]."',";
        		$query .= "'".$rawdata["NonoperatingGainsLosses"][$i]."',";
        		$query .= "'".$rawdata["OperatingExpenses"][$i]."',";
        		$query .= "'".$rawdata["OtherGeneralAdministrativeExpense"][$i]."',";
        		$query .= "'".$rawdata["OtherInterestIncomeExpenseNet"][$i]."',";
        		$query .= "'".$rawdata["OtherRevenue"][$i]."',";
        		$query .= "'".$rawdata["OtherSellingGeneralAdministrativeExpenses"][$i]."',";
        		$query .= "'".$rawdata["PreferredDividends"][$i]."',";
        		$query .= "'".$rawdata["SalesMarketingExpense"][$i]."',";
        		$query .= "'".$rawdata["TotalNonoperatingIncomeExpense"][$i]."',";
        		$query .= "'".$rawdata["TotalOperatingExpenses"][$i]."',";
        		$query .= "'".$rawdata["OperatingRevenue"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_metadata_eol
			$query = "INSERT INTO `reports_metadata_eol` (`report_id`, `CoverSheetTSO`, `CoverSheetTSODate`, `AuditorCode`, `AuditorOpinion`, `InventoryPolicy`, `NumberofShareholders`, `NumberofEmployees`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["CoverSheetTSO"][$i]."',";
        		$query .= "'".date("Y-m-d",strtotime($rawdata["CoverSheetTSODate"][$i]))."',";
        		$query .= "'".$rawdata["AuditorCode"][$i]."',";
        		$query .= "'".$rawdata["AuditorOpinion"][$i]."',";
        		$query .= "'".$rawdata["InventoryPolicy"][$i]."',";
        		$query .= "'".$rawdata["NumberofShareholders"][$i]."',";
        		$query .= "'".$rawdata["NumberofEmployees"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
			//reports_variable_ratios
			$query = "INSERT INTO `reports_variable_ratios` (`report_id`, `BookEquity`, `DebttoAssets`, `DegreeofCombinedLeverage`, `DegreeofFinancialLeverage`, `DegreeofOperationalLeverage`, `FreeCashFlow`, `DebttoEquity`, `AdjustedEPSBasic`, `AdjustedEPSDiluted`, `FreeCashFlowReturnonAssets`, `ReturnonAssets`, `ReturnonEquity`, `ReturnonInvestedCapital`, `RevenueperEmployee`, `CashRatio`, `CurrentRatio`, `FreeCashFlowMargin`, `LongTermCapital`, `LongTermDebttoLongTermCapital`, `LongTermDebttoTotalCapital`, `NetDebt`, `NetIncomeperEmployee`, `NetWorkingCapital`, `PretaxMargin`, `QuickRatio`, `TaxRate`, `TotalCapital`) VALUES (";
	        	$query .= "'".$report_id."',";
        		$query .= "'".$rawdata["BookEquity"][$i]."',";
        		$query .= "'".$rawdata["DebttoAssets"][$i]."',";
        		$query .= "'".$rawdata["DegreeofCombinedLeverage"][$i]."',";
        		$query .= "'".$rawdata["DegreeofFinancialLeverage"][$i]."',";
        		$query .= "'".$rawdata["DegreeofOperationalLeverage"][$i]."',";
        		$query .= "'".$rawdata["FreeCashFlow"][$i]."',";
        		$query .= "'".$rawdata["DebttoEquity"][$i]."',";
        		$query .= "'".$rawdata["AdjustedEPSBasic"][$i]."',";
        		$query .= "'".$rawdata["AdjustedEPSDiluted"][$i]."',";
        		$query .= "'".$rawdata["FreeCashFlowReturnonAssets"][$i]."',";
        		$query .= "'".$rawdata["ReturnonAssets"][$i]."',";
        		$query .= "'".$rawdata["ReturnonEquity"][$i]."',";
        		$query .= "'".$rawdata["ReturnonInvestedCapital"][$i]."',";
        		$query .= "'".$rawdata["RevenueperEmployee"][$i]."',";
        		$query .= "'".$rawdata["CashRatio"][$i]."',";
        		$query .= "'".$rawdata["CurrentRatio"][$i]."',";
        		$query .= "'".$rawdata["FreeCashFlowMargin"][$i]."',";
        		$query .= "'".$rawdata["LongTermCapital"][$i]."',";
        		$query .= "'".$rawdata["LongTermDebttoLongTermCapital"][$i]."',";
        		$query .= "'".$rawdata["LongTermDebttoTotalCapital"][$i]."',";
        		$query .= "'".$rawdata["NetDebt"][$i]."',";
        		$query .= "'".$rawdata["NetIncomeperEmployee"][$i]."',";
        		$query .= "'".$rawdata["NetWorkingCapital"][$i]."',";
        		$query .= "'".$rawdata["PretaxMargin"][$i]."',";
        		$query .= "'".$rawdata["QuickRatio"][$i]."',";
        		$query .= "'".$rawdata["TaxRate"][$i]."',";
        		$query .= "'".$rawdata["TotalCapital"][$i]."'";
        		$query .= ")";
	        	mysql_query($query) or die (mysql_error());
		}
	    }
	}
}
?>
